### ISSUE TITLE
Swaylock crashes and fails open when I turn off my display.

### ISSUE THREAD

**Issue by xorgy** [swaywm/swaylock#102]
I usually turn off my display when I lock my screen, but I've noticed swaylock will crash, and drop directly to the desktop when I turn off my display while it is locked.
It doesn't do this when I switch to another VT before turning off the display.

This is, for obvious reasons, a highly suboptimal behaviour for a lock screen.

**Comment by emersion** [comment]
Please provide a stack trace. You can do so by running `coredumpctl gdb` and then `bt full`.

**Comment by xorgy** [comment]
It's camera shy it seems, I'll try to gather a dump/trace.

**Comment by xorgy** [comment]
Either it's specifically set up not to dump, or it's not crashing. Either way, I had this issue again, and coredumpctl doesn't show any record of a crash.

**Comment by xorgy** [comment]
I'm going to try to start swaylock from a terminal with strace for the time being, and see if I get any interesting information as to why it closes.

**Comment by emersion** [comment]
Starting it with `WAYLAND_DEBUG=client` will be useful.

**Comment by emersion** [comment]
Anything in the sway logs?

**Comment by xorgy** [comment]
caught it!
Here's the end of the strace, makes sense! It exits with `EXIT_SUCCESS` after failing to operate on the wl_display (which is, as you would expect when the display is not connected, not present).
```
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\0\0\0\0(\0\1\0\0\0\0\0\0\0\22\0\0\0invalid obje"..., iov_len=1456}, {iov_base="", iov_len=2640}], msg_iovlen=2, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 40
write(2, "wl_display@1: error 0: invalid o"..., 41wl_display@1: error 0: invalid object 14
) = 41
exit_group(0)                           = ?
+++ exited with 0 +++
```
Here's the whole strace: <https://gist.github.com/xorgy/a9755c84e9c48022b2303b7b9f480f82>

**Comment by RedSoxFan** [comment]
This is swaywm/sway#3625. It's unfortunate that this is effecting the lock screen, but emersion is working on getting the appropriate wayland API changes merged that are needed to correctly fix the issue.  See https://github.com/swaywm/sway/issues/3625#issuecomment-513864693 for more information.

I'm going to close this since it affects every client and is not swaylock specific.
