### ISSUE TITLE
Option to show battery charge level

### ISSUE THREAD

**Issue by goetzc** [swaywm/swaylock#110]
Hi! It would be handy to have an option which can be set to show the battery charge level. Maybe something like `--show-battery-level`, defaulting to `BAT0`. 

This information is available at `/sys/bus/acpi/drivers/battery/*/power_supply/BAT0/capacity`

**Comment by emersion** [comment]
Sorry, we are not interested in this feature for swaylock. We encourage users who miss features in swaylock to fork it.
