### ISSUE TITLE
Pass through media control keys?

### ISSUE THREAD

**Issue by jfmcbrayer** [swaywm/swaylock#111]
I suspect this is one for the "WONTFIX" bin, but I thought I'd mention it.

Use case: I'm running Lollypop or Rhythmbox or something, listening to music on headphones. I want to adjust the volume while the screen has locked due to timeout (with swaylock being run by swayidle).

Under Gnome, the media keys (volume up/down, next/prev, etc) work while the screen is locked, as do the equivalent controls on a Bluetooth headset, and the screen brightness control keys. Under Sway + swayidle + swaylock, these keys don't work until the screen is unlocked.

I will not be surprised or upset if this is considered out of scope or insecure and closed.

**Comment by emersion** [comment]
You can use `bindsym --locked` so that the binding is active when the screen is locked.
