### ISSUE TITLE
Feature request: Prevent interaction but continue to display desktop

### ISSUE THREAD

**Issue by e00E** [swaywm/swaylock#112]
For example when viewing a film a user might want to keep displaying the film (instead of the lock screen) but still prevent the desktop from being interacted with.

I am not sure how unlocking should work visually. It could for example only draw the lock screen when some input is detected but otherwise continue to show the original desktop.

In a multi monitor setup the user could designate which monitors should continue to be displayed and which should show the lock screen.

I understand this might be out of scope for this project.

**Comment by emersion** [comment]
You could just run `swaylock` with a transparent background color.
