### ISSUE TITLE
Doesn't unlock after I typed the correct password

### ISSUE THREAD

**Issue by eternal-sorrow** [swaywm/swaylock#119]
In console I get this:
```
2019-12-31 00:47:31 - [swaylock-1.4/pam.c:101] pam_authenticate failed: invalid credentials
2019-12-31 00:47:35 - [swaylock-1.4/pam.c:101] pam_authenticate failed: invalid credentials
2019-12-31 00:47:39 - [swaylock-1.4/pam.c:101] pam_authenticate failed: maximum number of authentication tries exceeded
```
I'm pretty sure I'm typing the correct password, I don't have Caps Lock enabled and I type in correct layout. Also, I've seen https://github.com/swaywm/sway/issues/3631 and it's not my case, i have `/etc/pam.d/swaylock` file in place with `auth include login` line.

**Comment by ddevault** [comment]
You should report this bug to your distro and come back to us if they determine it's our fault.

**Comment by freed00m** [comment]
I also observe this behavior with swaylock 1.5 on Arch linux

I use systemd-homed it might be the cause. 
Hope I find the cultprit

**Comment by languitar** [comment]
Same thing here. Happens randomly. Has anyone in the meantime found out what is wrong here?

**Comment by BahadirAydin** [comment]
I had a similar issue where I was not able to unlock swaylock (specifically swaylock-effects). The workaround I have found is editing the file:

`/etc/security/faillock.conf`

There is a commented:
`deny = 3`
in the file you can just uncomment it and change it to whatever you want. 

In my case i made it 10. I will never mistype my password more than 10 times and it is quite unlikely for a attacker to brute-force it in 10 tries...

Source: https://wiki.archlinux.org/title/Security#Lock_out_user_after_three_failed_login_attempts

**Comment by mrlectus** [comment]
> /etc/security/faillock.conf

this was the issues with mine too but swaylock could have at least state that that was the problem
