### ISSUE TITLE
lock using "throw away" password

### ISSUE THREAD

**Issue by talbergs** [swaywm/swaylock#120]
I have a need to (I'm sure not many need this) to lock screen with other than my user password - i need something shorter and less secure - it can be a two letter thing passed as argument to swaymsg at the time of locking. `swaymsg --locke abc`

Is it possible to support this issue, if not is it easy to modify current source to have this?

**Comment by emersion** [comment]
Sorry, we're not interested in this feature upstream. It should be easy to fork swaylock to do this, though.

**Comment by talbergs** [comment]
Ok, I will consider that, thank you, for saying that this would be easy to do.
