### ISSUE TITLE
Still need setuid

### ISSUE THREAD

**Issue by bvn13** [swaywm/swaylock#123]
... even if I've set it up:

```
 ~  whereis swaylock
swaylock: /usr/local/bin/swaylock
 ~  ls -l /usr/local/bin | grep sway
lrwxrwxrwx. 1 root  root      32 янв  7 02:17 lock -> /home/bvn13/.config/sway/lock.sh
-rws--S---. 1 bvn13 bvn13 211704 янв  7 02:27 swaylock
 ~  swaylock
2020-01-07 02:49:05 - [shadow.c:18] swaylock needs to be setuid to read /etc/shadow
```

how to fix it?

**Comment by martinetd** [comment]
setuid is about taking the file owner's effective uid/gid, if you own the file that won't give executing it any more rights.

If you don't want anyone to execute it then root:bvn13 and rws--x--- is what you should aim for, read up about setuid.
