### ISSUE TITLE
Occasionally cannot enter password after swayidle

### ISSUE THREAD

**Issue by siyia2** [swaywm/swaylock#124]
Hello,

After letting my system to idle-lock-and turn dpms off with sway idle,sometimes i cannot enter my password upon resume in swaylock and i have to kill both sway and swaylock from a different tty,weird thing is i dont get any errors or anything and my screen lights up fine, i just cannot give any input from keyboard to swaylock.

my setings:

### Default power settings
 exec swayidle -w \
before-sleep 'swaylock -f -c 000000' \
timeout 3601 'systemctl suspend' \
timeout 301 'swaylock -f -c 000000' \
timeout 302 'swaymsg "output * dpms off"' \
resume  'swaymsg "output * dpms on"' ; 'swaymsg "input '*' xkb_layout 'us'"' 

### Sys Setup
Manjaro Linux,sway 1.2, kernel 5.4, amdgpu RX550

**Comment by siyia2** [comment]
I setted up my keyboard layouts properly in sway config:

### KB LAYOUTS

input "*" {
    xkb_layout us,gr
    xkb_options grp:alt_shift_toggle
}
### Default power settings

exec swayidle -w
before-sleep 'swaylock -f -c 000000'
timeout 3601 'systemctl suspend'
timeout 301 'swaylock -f -c 000000'
timeout 302 'swaymsg "output * dpms off"'
resume 'swaymsg "output * dpms on"'

but swaylock still has the problem, on the other hand i tested i3locks and it works reliably, so i consider this to be swaylock specific bug.

**Comment by siyia2** [comment]
An easy way to test this is:

bindsym $mod+f11 exec pkill -nx swayidle && exec  swayidle -w \
timeout 2 'swaylock -f -c 000000' \
timeout 4 'swaymsg "output * dpms off"' \
resume  'swaymsg "output * dpms on"' \

in your sway config.press the hotkey and let the screen lock and dpms to turn completely off,after that move your mouse unti the screen lights up and try to eneter passwrd,if it doesnt crash repeat around 5-6 times.

**Comment by siyia2** [comment]
i can also reproduce the issue by pressing enter twice without moving the mouse and letting the screen light up, but no way to enter password in swaylock

**Comment by siyia2** [comment]
i've managed to hit the same issue with i3lock+sway 1.2

**Comment by siyia2** [comment]
If i execute swaylock  outside of swayidle it never crashes,issue happens between
'swaymsg "output * dpms off"'  and 'swaymsg "output * dpms on"'

**Comment by siyia2** [comment]
[swaylocktrace.txt](https://github.com/swaywm/swaylock/files/4040691/swaylocktrace.txt)

**Comment by siyia2** [comment]
i captured trace from when swaylock crashes using strace, please have a look at it

**Comment by siyia2** [comment]
updating to latest sway-git and wlroots-git in master solves the issue

**Comment by spikespaz** [comment]
I still have this issue all the time. Using NixOS, Hyprland, Swayidle, and Swaylock.
