### ISSUE TITLE
swaylock crashes on gnome

### ISSUE THREAD

**Issue by soloturn** [swaywm/swaylock#130]
gnome does not have a screen locking any more:
https://unix.stackexchange.com/questions/86221/how-can-i-lock-my-screen-in-gnome-3-without-gdm

swaylock dumps a core with newest gnome:

```
$ swaylock 
swaylock: ../swaylock-1.5/main.c:1183: main: Assertion `state.compositor && state.layer_shell && state.shm' failed.
Aborted (core dumped)
$ yay -Q 
gnome-shell 1:3.34.3-1
mutter 3.34.3+14+g59e9b073a-1
```

should it work with gnome, and if yes, how to debug?

**Comment by RedSoxFan** [comment]
Gnome does not support the [layer-shell](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml) protocol. swaylock will not work on Gnome.

**Comment by soloturn** [comment]
here is a little more information for this topic, jadal saying "What can be done, however, is to make it possible for libmutter users, including GNOME Shell, to implement their own Wayland protocols. That way some compositor that wants to enable the user to plug in whatever panel, notification popup provider, etc it wants, can implement whatever protocol would be necessary for doing so."

https://gitlab.gnome.org/GNOME/mutter/issues/973
