### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [swaywm/swaylock#131]
I would like to point out that an identifier like “[`_SWAYLOCK_H`](https://github.com/swaywm/swaylock/blob/a7404e109643bffb77cb63b6f22fc5d46a7cead2/include/swaylock.h#L1 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by emersion** [comment]
You already opened an issue for that on the Sway repo. Please send a pull request.
