### ISSUE TITLE
[Feature Request] Option to *not* daemonize and/or run command after unlocking?

### ISSUE THREAD

**Issue by akobel** [swaywm/swaylock#137]
`--daemonize` is the default, but there is no option to *not* daemonize, AFAICS (at least in Arch's current swaylock 1.5). Notably, this makes the proposed workarounds for #56 and #129 wrong, probably without people noticing them fail) This (most likely unexpected) behavior is demonstrated by `date +%T.%N; swaylock -d; date +%T.%N`; the second `date` command is executed within milliseconds, i.e. after locking, *not* on unlock.

Example use cases: re-enabling muted sound, restoring decreased brightness, calling `physlock -L` to unlock previously disabled console switching, re-enabling SysRq (note that physlock's `-s` option only works while physlock is running, so the `-s` for a swaylock wrapper like `physlock -sl; swaylock --no-daemonize; physlock -L` would not work even if `--no-daemonize` would exist)...

**Comment by emersion** [comment]
`--daemonize` is not the default.

**Comment by akobel** [comment]
Uh, gosh. Shame on me, didn't RTFM careful enough: it's *i3lock's* default. And it is *my* current default, because I pulled it in the config file for no good reason... Sorry for the noise.
