### ISSUE TITLE
Swaylock needs to be setuid to read /etc/shadow

### ISSUE THREAD

**Issue by southern-tools** [swaywm/swaylock#142]
Hello, I am not able to lock the screen under Gentoo (openrc without consolekit, pam, elogind).
I am getting: `[swaylock-1.5/shadow.c:18] swaylock needs to be setuid to read /etc/shadow` and if I: `chmod +s /usr/bin/swaylock`, then I get: `[swaylock-1.5/shadow.c:36] Unable to drop root (we shouldn't be able to restore it after setuid): Success`.
I reported a similar problem about permissions on swaywm/sway one year ago ([#3363](https://github.com/swaywm/sway/issues/3363)), but happily that is solved.
Here is my log: [sway.log](https://github.com/swaywm/swaylock/files/4607941/sway.log)
Thank you very much for your help.

**Comment by KevFrancisco** [comment]
In case anyone comes across this in the future, `chmod a+s /usr/bin/swaylock` fixed this issue for me, as in the documentation.

Ubuntu 20.10 Groovy, installed waybar from apt, then built from source on top of it.

**Comment by rileyrg** [comment]
hmm doesnt work for guix - read only filesystem...

**Comment by emturner** [comment]
@rileyrg not sure if you got this working, but I managed to earlier - had to add swaylock in as a `setuid` program in the `operating-system` declaration:

```guile
(setuid-programs
    (append
      (list (file-like->setuid-program
	      (file-append
		(specification->package "swaylock")
		"/bin/swaylock")))
      %setuid-programs))
```
from the [guix reference](https://guix.gnu.org/manual/en/html_node/Setuid-Programs.html)

then make sure you don't have `swaylock` installed in your user profile as that will get used over the system one (which is the one that will be in `/run/setuid-programs`, and it should be working after `reconfigure` 😄

**Comment by rileyrg** [comment]
This doesn't work if you're using guix in its package manager only mode I was told. But thank you. I stopped using it tbh.
