### ISSUE TITLE
Clear password input on Ctrl+Backspace

### ISSUE THREAD

**Issue by holykol** [swaywm/swaylock#157]
See the title. Some users would also expect input to clear itself after holding backspace for some time (e.g. 600ms).

**Comment by aarongable** [comment]
Agreed, this would be nice.

I will note that there are three other key combinations which clear the input already:
* [ESC](https://github.com/swaywm/swaylock/blob/235b925df7e1bb82d98f1ac8c02e8f85d0a54ee9/password.c#L118-L123)
* [Ctrl+C](https://github.com/swaywm/swaylock/blob/235b925df7e1bb82d98f1ac8c02e8f85d0a54ee9/password.c#L148-L156)
* [Ctrl+U](https://github.com/swaywm/swaylock/blob/235b925df7e1bb82d98f1ac8c02e8f85d0a54ee9/password.c#L149-L156)

I'll also note that key-repeat (which would allow holding backspace to delete multiple characters in rapid succession) has been [landed on master](https://github.com/swaywm/swaylock) but not yet included in a tagged release.
