### ISSUE TITLE
Accept colors prefixed by a #

### ISSUE THREAD

**Issue by elegaanz** [swaywm/swaylock#160]
Sway accepts colors prefixed with a `#` (`#ff00aa` for instance), but swaylock wants them without this prefix (just `ff00aa`). It makes it much harder to define variables in your sway config for your colors and to re-use these variables both for the sway config and as arguments for swaylock (spawned with `exec swayidle` in the sway config). A workaround would be to define the variable twice, once with the `#`, once without. But that doesn't work very well with programs like `wal` that automatically generate a sway theme according to your background image.

A simple solution would be to accept the `#` for colors, by just removing it if is here when parsing a color.

If that seems to be a good idea to you, I can even try to contribute a patch to fix this issue.

**Comment by Xyene** [comment]
This seems like a good idea. i3lock does this too: https://github.com/i3/i3lock/blob/master/i3lock.c#L1065-L1067

**Comment by elegaanz** [comment]
After checking the code a little bit more in details, I realized that colors with a `#` where already accepted! The trick is that the shell consider it is a comment, so the workaround is just to wrap it in single quote, like so `swaylock --color '#ffaaff'`.
