### ISSUE TITLE
[SOLVED] Swaylock not working on Gentoo Linux

### ISSUE THREAD

**Issue by MuhammedTaha02** [swaywm/swaylock#169]
Hello. I using swaywm on gentoo. But swaylock is not working. Although I have typed my password correctly, it does not accept my password. And there's this mistake in the back. How can i fix this problem?

![image](https://user-images.githubusercontent.com/62564400/110286228-9fd23280-7ff5-11eb-9281-136840e55ed2.png)

**Comment by kennylevinsen** [comment]
Error 6 is PAM_CONV_ERR if I recall correctly.

Your swaylock PAM stack (/etc/pam.d/swaylock) appears to be failing. Check syslog and auth logs.

**Comment by MuhammedTaha02** [comment]
> Error 6 is PAM_CONV_ERR if I recall correctly.
> 
> Your swaylock PAM stack (/etc/pam.d/swaylock) appears to be failing. Check syslog and auth logs.

Sorry I couldn't find a log file like authorization or syslog under /var/log

**Comment by kennylevinsen** [comment]
> Sorry I couldn't find a log file like authorization or syslog under /var/log

Being on Gentoo, this depends on your configuration (e.g. systemd or not, syslog provider and configuration, etc.).

**Comment by MuhammedTaha02** [comment]
> > Sorry I couldn't find a log file like authorization or syslog under /var/log
> 
> Being on Gentoo, this depends on your configuration (e.g. systemd or not, syslog provider and configuration, etc.).

I know. Where exactly is the problem I'm trying to solve it. There is a problem between Pam and Swaylock but how can I find a problem?

**Comment by kennylevinsen** [comment]
> how can I find a problem?

1. Look for log messages from PAM modules to see if there is a clue.
2. Some PAM modules have a verbose flag that can be set in the stack - refer to each module's documentation.
3. Take PAM modules out of the stack (/etc/pam.d/swaylock) one at a time to see if you can find one that is failing. Don't just remove entire includes though, and beware of modifying shared files as you may lock yourself out of your system accidentally.

Steps after that involve debugging with strace and gdb.

**Comment by MuhammedTaha02** [comment]
> > how can I find a problem?
> 
> 1. Look for log messages from PAM modules to see if there is a clue.
> 2. Some PAM modules have a verbose flag that can be set in the stack - refer to each module's documentation.
> 3. Take PAM modules out of the stack (/etc/pam.d/swaylock) one at a time to see if you can find one that is failing. Don't just remove entire includes though, and beware of modifying shared files as you may lock yourself out of your system accidentally.
> 
> Steps after that involve debugging with strace and gdb.

There is only one module in the /etc/pam.d/swaylock file. This is it
**auth include login**

Which command should I print with Strace?

**Comment by kennylevinsen** [comment]
> There is only one module in the /etc/pam.d/swaylock file. This is it
> auth include login

As the name suggests, that's an include. It includes the "login" stack's auth sections (lines starting with "auth"), which may in turn include other stacks.

Be careful of the warning I posted - you may want to inline the modules directly into your swaylock file and experiment there, instead of modifying included files that are shared with other tools as messing up the files may lock yourself out of your system.

> Which command should I print with Strace?

Complete 1 through 3 first.

**Comment by MuhammedTaha02** [comment]
Problem is solved;

Solution : sudo chmod u+s /sbin/unix_chkpwd
