### ISSUE TITLE
Session unlock after simulated swaylock crash

### ISSUE THREAD

**Issue by vulpicastor** [swaywm/swaylock#174]
I performed an experiment where I ran `sleep 30 && pkill -9 swaylock` in the terminal before locking the screen to simulate what happens if swaylock crashed. I was surprised to find that my session simply returned, unlocked.

In a similar vein to #164, is this intended behavior? Because if it is, then screenlocking under sway is no safer than the old days under Xorg.

Under the current design, is it at all possible for sway to at least terminate the user session if the screenlocker crashes? That behavior may be annoying, but at least it doesn't leave a gaping security hole.

**Comment by emersion** [comment]
Yes. this is intended behaviour. You can set your lock command to `swaylock || swaymsg exit` if you want to quit Sway on swaylock failure.

See https://github.com/swaywm/wlroots/issues/2706 for proposals to improve the status quo.
