### ISSUE TITLE
Allow Ctrl+alt+Fn to switch to other VT

### ISSUE THREAD

**Issue by eternalinflation** [swaywm/swaylock#177]
Allow Ctrl+Alt+Fn to switch to other VT during swaylock.
Current behavior is that Ctrl, Alt, and Function keys are ignored. Entering the passphrase works OK.

**Comment by emersion** [comment]
This isn't done by swaylock, this is done by sway, and it doesn't care whether swaylock is active or not.

**Comment by eternalinflation** [comment]
Sorry, yes, it actually works with sway. I tested swaylock with another compositor.
