### ISSUE TITLE
unlocked screen is shown for a moment on `output enable`

### ISSUE THREAD

**Issue by 532910** [swaywm/swaylock#185]
https://user-images.githubusercontent.com/14617699/120107647-87903080-c16a-11eb-8610-6ea5c205f03c.mp4

```
bindswitch --locked {
        lid:on  output $laptop_display disable
        lid:off output $laptop_display enable
}
```

**Comment by Brendan-McDonnell** [comment]
I've had success with
```
bindswitch --locked lid:on exec swaylock -f; sleep 0.25; output $laptop disable
```
My best guess as to why locking and then waiting before disabling the display works is some sort of buffering issue, where the last rendered frame is shown when the display is enabled again. By locking before disabling, that last rendered frame is `swaylock`'s output. The short sleep is required, presumably to wait for the frame buffer to be full of "locked" frames only. This is just my best guess, though.

Note that it can take several seconds for my screen to turn off after i close the lid, not the 0.25 you might expect. I've also occasionally had to close and open my laptop if I reopen the lid at just the wrong time. I think that time is when the screen actually turns off, but this is a rare occurrence so I'm not sure. Besides this occasional oddity, this has worked consistently for me.

**Comment by danieldg** [comment]
FYI: this is fixed in 1.6 when used with compositors that support the lockscreen protocol (see https://github.com/swaywm/swaylock/pull/219 and https://github.com/swaywm/sway/pull/6879).

**Comment by ifreund** [comment]
@danieldg actually, this isn't fixed with ext-session-lock on sway yet, see https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/186

**Comment by emersion** [comment]
This is a compositor bug, not a swaylock bug.
