### ISSUE TITLE
show failed attempts after successful login

### ISSUE THREAD

**Issue by 532910** [swaywm/swaylock#189]
I believe the number of failed attempts should be shown after successful login. The same as xscreensaver does.

**Comment by emersion** [comment]
Sorry, NACK, but please feel free to implement in a fork.

**Comment by 532910** [comment]
May I ask for some short explanation why?

**Comment by emersion** [comment]
I want to keep swaylock small and simple, so I'd rather not add new features at this point.

**Comment by 532910** [comment]
I'd not say this is a new feature just a different order of existing ones. Showing failed attempts before successful login is a some kind of security issue.
