### ISSUE TITLE
Proposal: Provide hooks for unlock events 

### ISSUE THREAD

**Issue by glyh** [swaywm/swaylock#191]
Thus we can execute some commands to make the computer ready for use. For example, brightness, battery strategy, etc.

**Comment by emersion** [comment]
NACK. Instead, monitor swaylock's exit. e.g. run `swaylock; echo "Unlocked!"` instead of just `swaylock`.

**Comment by eugenemw** [comment]
If am not mistaken this solution would be incompatible if one demonizes `swaylock`,
because it seems  `echo "Unlocked!" is ran at lock time.
Demonization is useful for example in this use case `bindsym $win+s exec swaylock -f -e && sudo systemctl suspend && echo "Unlocked!" `

**Comment by eugenemw** [comment]
The aforementioned is easily solved using this command instead `sudo systemctl suspend && swaylock -e && echo "Unlocked!"`
