### ISSUE TITLE
Keyboard input bypasses swaylock when monitor is off, can interact with focused window underneath

### ISSUE THREAD

**Issue by and-reas-se** [swaywm/swaylock#204]
How to reproduce:

1. Use sway as window manager (possibly works with others, but only one I tested with sway).
2. Leave a terminal window focused on screen (I used alacritty if that makes a difference).
3. Lock computer with swaylock using keyboard shortcut that starts it.
4. Turn off monitor (connected trought displayport in my case).
5. With monitor off, type some terminal command on your keyboard and press enter.
6. Turn monitor back on, and enter your password to unlock computer.
7. You will now see that the command you typed when the monitor was off and your computer was locked was executed in the terminal.

Probably related to #188. Seems like a pretty significant security issue. Let me know if you need more details about my configuration.

**Comment by maxrp** [comment]
I've observed this as well, although I also use Alacritty I can replicated this behavior with Sublime Text, Firefox or Alacritty as the underlying window.

I concur on steps to replicate -- except that it seems to work with any highlighted window.

**Comment by danieldg** [comment]
Note: I've not tried to reproduce, but I think this might be caused by swaylock not having an active window when all monitors are disconnected ("off" can sometimes mean "disconnected").  In that case, there's no window for an input grab to be associated with.  If this is the cause, changing swaylock to always make a window (even if no outputs are present) might be needed.  Changing the compositor to not give back input focus just because a locker closes (https://github.com/swaywm/wlroots/issues/2706) will fix this and many other swaylock security issues.

**Comment by baldimir** [comment]
I am observing this too. Sometimes I see the part of my password that I type while my external screen is off in a text input if I have one selected before I lock my computer. This is a serious security concern to me.

**Comment by eloeffler-fhnw** [comment]
There has been a merge request on wlroots for several months months which is currently not in a working state because it needs to be adapted to changes in wlroots.

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3165

**Comment by markstos** [comment]
Is the solution in #219 ready for testing via Sway Yet?

**Comment by eloeffler-fhnw** [comment]
> Is the solution in #219 ready for testing via Sway Yet?

It's already merged. I've just tested with swaylock version 6979ab4 (Jan 20 2022, branch 'master') on Manjaro 21.2.3.

Keyboard isn't bypassing the lockscreen anymore.

**Comment by emersion** [comment]
Nope, Sway doesn't support ext-session-lock atm.

**Comment by nyancow** [comment]
> Nope, Sway doesn't support ext-session-lock atm.

Is support for `ext-session-lock` planned? If so, where is it tracked?

**Comment by emersion** [comment]
Patches welcome.

**Comment by PanAeon** [comment]
I experience the same issue. Does `ext-session-lock` help?

**Comment by WhyNotHugo** [comment]
> I experience the same issue. Does ext-session-lock help?

Yes. This issue cannot be reproduced with the `ext-session-lock` protocol. However, you'll need to build sway from `master`, since this feature hasn't made it into a stable release yet.

**Comment by Smona** [comment]
ext-session lock is now released in [sway 1.8](https://github.com/swaywm/sway/releases/tag/1.8)! Maybe this issue can be closed now?

**Comment by primalmotion** [comment]
This happened to me again this morning with latest master. Impossible to type on swaylock, switched tty to SIGUSR1, my terminal was filled with the gibberish I typed. I can easily reproduce

**Comment by primalmotion** [comment]
https://github.com/swaywm/swaylock/assets/208711/240ccb87-5664-441f-b65f-b801fbec68a5

you don't see it on the video obviously, but the laptop suspends. when swaylock shows, it's after I wake up the system. You don't see it either, but while swaylock is there, I type. finally I hit a shortcut I added to send sigusr1 to swaylock. You can see that what I typed has been typed in my terminal

**Comment by WhyNotHugo** [comment]
On Fri, 12 May 2023, at 22:54, primalmotion wrote:
> 
> 
> This happened to me again this morning with latest master. Impossible to type on swaylock, switched tty to SIGUSR1, my terminal was filled with the gibberish I typed. I can easily reproduce
> 

Latest master of swaylock? Which sway version?

**Comment by primalmotion** [comment]
@WhyNotHugo yeah latest master of swaylock, and I use latest master of Hyprland

**Comment by WhyNotHugo** [comment]
On Fri, 12 May 2023, at 23:21, primalmotion wrote:
> 
> 
> @WhyNotHugo <https://github.com/WhyNotHugo> yeah latest master of swaylock, and I use latest master of Hyprland
> 

Sounds like a bug in Hyprland, see discussion in https://github.com/hyprwm/Hyprland/issues/799

**Comment by WhyNotHugo** [comment]
On Fri, 12 May 2023, at 23:27, Hugo Osvaldo Barrera wrote:
> 
> 
> On Fri, 12 May 2023, at 23:21, primalmotion wrote:
>> 
>> 
>> @WhyNotHugo <https://github.com/WhyNotHugo> yeah latest master of swaylock, and I use latest master of Hyprland
>> 
> 
> Sounds like a bug in Hyprland, see discussion in https://github.com/hyprwm/Hyprland/issues/799

Scrub that, I'm thinking of another scenario.

**Comment by primalmotion** [comment]
what bothers me is this kernel parameter that causes it. I don't understand the link

**Comment by kennylevinsen** [comment]
Anything causing input to end up in the wrong window when using ext_session_lock_v1 would be a compositor focus bug. Focus calculations quickly end up with a lot of edge cases, so it's tricky to get right. Make sure that protocol is in use though - layer shell and input inhibitor is a another beast entirely.

no_console_suspend might just affect some timings or suspend order that affect inp7r events and focus calculation triggers.

**Comment by primalmotion** [comment]
Ok that makes sense. It seems Hyprland is arleady having several issues with multimonitors swaps combined with suspend. So yeah no_console_suspend is probably making the existing bug worse. which is good in a sense :) thanks!

**Comment by ninetailedtori** [comment]
Has there been a report regarding this issue on the Hyprland repo yet? Because it's very annoying XD

**Comment by kennylevinsen** [comment]
> Has there been a report regarding this issue on the Hyprland repo yet? Because it's very annoying XD

That would be a question for the Hyprland repo, not the swaylock one.
