### ISSUE TITLE
Lock failing (socket connection fail?)

### ISSUE THREAD

**Issue by mefromthepast** [swaywm/swaylock#206]
Sometimes, after reopening the closed lid of my laptop, instead of a lock screen I am returned to the TTY and see the following messages (not sure in what way the first 3 lines are connected to the issue or if they are at all, I just took a picture the last time it happened and did not confirm that those messages are there all the time - I suppose that at least the `X11` message is connected to some different application). Also, the last message appeared in the logs 10+ times.

```
The X11 connection broke (error 1). Did the X11 server die?
Error: Wayland connection experienced a fatal error: -1
Error: Temperature adjustment failed.
00:00:00.000 [common/ipc-client.c:67] Unable to connect to /run/user/1000/sway-ipc.1000.1489.sock
```

Probably related to #164

**Comment by kennylevinsen** [comment]
If you see the kernel console, then it's sway that crashed, not swaylock. Please open an issue for sway with appropriate information.
