### ISSUE TITLE
request for release / tag

### ISSUE THREAD

**Issue by prometheanfire** [swaywm/swaylock#229]
There's been some fixes since 2020 when 1.5 was tagged, it'd be nice to have a new release.

https://github.com/swaywm/swaylock/commit/1d1c75b6316d21933069a9d201f966d84099f6ca is not cleanly apply-able to 1.5 and we'd like to get some crash fixes in https://bugs.gentoo.org/834716

https://github.com/swaywm/swaylock/compare/1.5...master

Thanks

**Comment by emersion** [comment]
Indeed, done: https://github.com/swaywm/swaylock/releases/tag/1.6
