### ISSUE TITLE
Fullscreen window visible after lock

### ISSUE THREAD

**Issue by alextsits** [swaywm/swaylock#236]
I use `alacritty` as my terminal emulator, and sway as window manager.

I noticed if alacritty is fullscreen when I start `swaylock`, the alacritty window is visible after locking, although, the window does not refresh, and it does not get any input.

Alacritty version: 0.11.0.1975.g5c51d528-1
Swaylock version: 1.6.r6.gfad5bc2-1

I'm not sure whose bug it is, or if it's reproducible with other apps. Let me know if there is any other info I could provide.

**Comment by alextsits** [comment]
I just noticed that this happens for most (if not all) `xwayland` applications as well.

Steps to reproduce:
1) Start any xwayland application
2) Make its window fullscreen
3) Start swaylock

Expected result:
1) Screen turns to black, with the usual ring appearing on input

Actual result:
1) The fullscreen window remains visible, albeit "frozen".

**Comment by alextsits** [comment]
I need to note that this is **not** an `xwayland`-specific bug. It happens with `alacritty` as well, running in native `wayland`. I made sure by disabling `xwayland` support in `sway` and reproducing with `alacritty`.

**Comment by kennylevinsen** [comment]
what version of sway? Master with the newly landed ext-session-lock-v1 support?

**Comment by alextsits** [comment]
@kennylevinsen yes. The exact sway version is `r6918.c85d9af2b-1`.
But I'm not sure how ext-session-lock-v1 works. Is it something I need to configure on my side for it to work? Does it work out of the box? I haven't done anything to enable it explicitly.

**Comment by alextsits** [comment]
@kennylevinsen I confirm that `ext-session-lock-v1` is enabled. I tested by starting `swaylock` and then `kill -9` it from a tty. The session remained locked. This wouldn't be the case if `ext-session-lock-v1` wasn't enabled.

**Comment by stromnet** [comment]
+1 here:

Just bumped sway from r6910.2dace6b8-1 -> r6918.c85d9af2-1, and chromium 100.0.4896.127-2 -> 101.0.4951.64-1 (and alot of other things). Swaylock 1.6-1.

On one output I have a chromium in fullscreen. When I lock with swaylock, that output is no longer hidden. I cannot interact with it, it seems, but the contents is still there.

No for_window customizations at all for the chromium windows.
Launched with `env LANG=en_UK /usr/bin/chromium %U'`

**Comment by danieldg** [comment]
This is a sway bug; the ext-session-lock surface is not being considered when determining if direct scan-out should be used.

https://github.com/swaywm/sway/pull/6844 reworks the rendering path and will fix this issue.

**Comment by stromnet** [comment]
Resolved with above fix, thanks!
