### ISSUE TITLE
Ignore screenshot failure

### ISSUE THREAD

**Issue by ldelossa** [swaywm/swaylock#242]
Hey, 

Im using swaylock with my laptop and two external monitors. 

When I close my laptop lid with two other monitors attached and run swaylock on the CLI, swaylock does not start. Instead it throws an error about "Unable to copy screenshot" and then fails to create the overlay.

**Comment by emersion** [comment]
swaylock doesn't perform any screenshot. This sounds like an issue in your configuration files.
