### ISSUE TITLE
swaylock ignores A portion of rgba specification in -c parameter.

### ISSUE THREAD

**Issue by dnfm** [swaywm/swaylock#248]
I have one monitor I use an image of pixel.png (which is a 1x1 transparent png), and a colour specification of ffffff00 which used to work to leave one monitor visible when the computer was locked (it runs grafana/security cameras), and at some point it stopped working.

No combination of -i or -c parameters seems to work.  Just doing swaylock -c ffffff00 I would expect to lock the screen but still be visible, but it doesn't.

**Comment by emersion** [comment]
Yes. The new locking Wayland protocol makes it so surfaces underneath the lock screen are not painted, by design.

**Comment by dnfm** [comment]
Is there a way to disable that/make it work like it did before?
