### ISSUE TITLE
`(question)` is it safe to lock under swayidle `after-resume` ?

### ISSUE THREAD

**Issue by asklow** [swaywm/swaylock#260]
Swaylocking under swayidle `before-sleep` increases timeout to 7 more seconds for me.
So I moved swaylock into `after-sleep` option, which fixes this timeout delay.

Question is, is it safe to do this ? (since I'm locking after I resume).

**Comment by kennylevinsen** [comment]
There will be a short period after resume where swaylock has yet to start, the duration of which is system dependent. This is suboptimal, security-wise.

**Comment by kennylevinsen** [comment]
By popular definition, a delay between the machine waking up and the session being locked would not be considered safe. Your machine might be ready and taking input before anything is shown on screen.
