### ISSUE TITLE
pam_tally: error opening /var/log/faillog

### ISSUE THREAD

**Issue by mdeff** [swaywm/swaylock#27]
I'm getting the following errors when unlocking my screen:
```
swaylock[13620]: pam_tally(swaylock:auth): Error opening /var/log/faillog for update
swaylock[13620]: pam_tally(swaylock:auth): Error opening /var/log/faillog for read
```

`pam_tally` is used to keep a count on attempted accesses, and deny access if too many attempts fail. I'm using the default PAM configuration provided by Arch Linux. I think `pam_tally` is invoked from `/etc/pam.d/system-login` (included from `system-local-login` from `login` from `swaylock`).

I understand that using `pam_tally` is a configuration option. But I think that it shouldn't fail with swaylock.

**Comment by Emantor** [comment]
Do you get the same error when logging into a tty?

**Comment by mdeff** [comment]
I don't.

**Comment by daenney** [comment]
The problem appears to stem from the PAM config Sway ships. For `pam.linux` it has:

```
auth include login
```

But at least on Arch this needs to be:

```
auth include system-auth
```

The default provided by Swaylock probably works on Debian systems, but not everywhere. This appears to be similar to the i3lock bug in Arch: https://bugs.archlinux.org/task/31544. The swaylock bug is here: https://bugs.archlinux.org/task/53358. Depending on your distro, you might need to file a bug with them too.

**Comment by daenney** [comment]
Also, if you're running Arch, do check you don't have any `.pacnew`'s in `/etc/pam.d`. `system-login` moved to using `tally2`

**Comment by mdeff** [comment]
The move to `tally2` indeed suppressed the errors.
