### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by DavidHenryThoreau** [swaywm/swaylock#273]
Since update `swaylock --version swaylock version 1.7` the mouse cursor appears when screen is locked, i can also move the cursor.
How can I disable the mouse cursor ?

**Comment by abvee** [comment]
I can second having the same problem. Updated to version 1.7, and the mouse cursor appears in the lock screen. Previous versions did not have this issue. My distro is Arch Linux, so if this is an Arch problem, please let me know.

`swaylock -d -f` shows nothing out of the ordinary, and no errors are reported. `sway --debug` also yielded anything useful when I lock the screen.....

If there is anything I can do to provide more information, please let me know :D

**Comment by DavidHenryThoreau** [comment]
`swaylock -d -f -i $HOME/.config/sway/wallp.jpg -u` still shows mouse cursor

**Comment by emersion** [comment]
This patch should fix it: https://github.com/swaywm/sway/pull/7386
