### ISSUE TITLE
Background color alpha not working

### ISSUE THREAD

**Issue by jiexi** [swaywm/swaylock#278]
Version 1.7

`swaylock -c 00000000` used to produce a completely transparent lock screen, but now it is fully opaque regardless of the alpha provided

**Comment by emersion** [comment]
This is by design. Sway no longer paints the regular desktop when the lockscreen is active for security reasons.

**Comment by ckcr4lyf** [comment]
How about adding a flag for it or override? It was quite useful to setup something in a "kiosk" mode of sorts, such that the screen could be auto updating with graphs or a video or something while you're walking around, which others can see, but not do anything on the system. (I used to use [xtrlock](https://manpages.ubuntu.com/manpages/xenial/man1/xtrlock.1x.html) on X11)

This way the user needs to explicitly opt in. (Unless I am slightly misunderstanding - and the functionality to enable alpha is removed due to security reasons)

**Comment by ckcr4lyf** [comment]
Alternatively, could you hint as to which MR removed the functionality? I've not done any Wayland programming before, but it would be a fun place to start (try and implement xtrlock)

I went through https://github.com/swaywm/swaylock/compare/1.6...1.7 but not too sure

**Comment by emersion** [comment]
A flag won't work. One would need to keep using layer-shell instead of ext-session-lock, and accept that the lockscreen is insecure. Sway will drop support for input-inhibit soon.

**Comment by Icelk** [comment]
This is a regression on compositors other than sway. I used to have swaylock be transparent and set the `lockscreen` layer to be blurred. Now, the background is completely transparent, showing everything on my desktop. So if you're using security as an argument, this change certainly made it worse.

**Comment by emersion** [comment]
That sounds like a bug in the compositor you're using.

**Comment by Icelk** [comment]
Please correct me if I'm wrong, but the changes made swaylock **not** appear as a layer anymore?

**Comment by emersion** [comment]
Yes. The new protocol doesn't use layer-shell. Compositors are expected to not paint anything else when swaylock is active.

**Comment by Icelk** [comment]
I understand.

Is there any way for me to use layer-shell or else achieve the blurred background effect with a locked screen?

**Comment by Xyene** [comment]
You can have a script that takes a screenshot, blurs it, and then uses it as the swaylock background.

**Comment by Icelk** [comment]
Right, I've seen that solution elsewhere. But it's suboptimal: the blur happens on the CPU, and often doesn't use the same algorithm as the compositor. Guess I'll have to downgrade :(

**Comment by thialfi17** [comment]
Please can you add a note to the man page that this no longer works? I spent a long time trying to debug why this might be broken and looking for open issues before finding this issue that has been closed. I can understand the reason why this behaviour has changed/isn't supported, but it would have been good to have some kind of note that the transparency doesn't work (at least as it used to/as expected) when using the "--color RRGGBBAA" option
