### ISSUE TITLE
package size issue reported on gentoo

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/swaylock#28]
Hi,
Here we have:
* Digest verification failed:
 * /usr/local/portage/dev-libs/swaylock/swaylock-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2337
 * Expected: 2338

It builds though, but doesn't integrate well in gentoo's package management system (portage)

Thks 4 ur attention.

**Comment by emersion** [comment]
This is a Gentoo issue. Report it to the Gentoo package maintainers.
