### ISSUE TITLE
[Feature request] add keybindings to swaylock

### ISSUE THREAD

**Issue by nakibrayan3** [swaywm/swaylock#293]
when i close my laptop lid it activates swaylock before sleep

and when i am watching a video and i close my laptop lid that video is paused

but when i open my laptop lid it start playing the video immediately

i want to have a keybinding to pause any media playing before i continue typing my password

Example:
bind XF86AudioPlay exec playerctl play-pause

**Comment by kennylevinsen** [comment]
Just use `bindsym --locked` in sway to allow the keybinding to work while a lock screen is active. No need for swaylock to have its own keybindings.

Alternatively, if you always want things to pause when your lock screen comes up, call pause (not play-pause) before the swaylock command.
