### ISSUE TITLE
Add the ability to create our own lock screen layouts

### ISSUE THREAD

**Issue by Parmjot-Singh** [swaywm/swaylock#298]
I would like to see the ability to customise the layout of the lock screen, including but not limited to:
- Moving where the lock indicator is
- Other types of lock indicators, such as a bar
- Allow the user to separate the clock from the lock indicator
Obviously, this sounds very needy, and people would say to make it yourself, but I'm still learning C so I wouldn't really know how to do this. :/

**Comment by emersion** [comment]
This sounds out of scope for swaylock, sorry. Feel free to make this happen in a fork of course.

**Comment by Parmjot-Singh** [comment]
Never a better time to learn C :')
