### ISSUE TITLE
wl_buffer destroyed before surface committed

### ISSUE THREAD

**Issue by wmww** [swaywm/swaylock#299]
In [render_frame_background()](https://github.com/swaywm/swaylock/blob/31ebd85fe09701146b7275de1ec8c8e9ce3c15c6/render.c#L72) a buffer is created, attached and destroyed before it's surface is committed. Swaylock seems to expect the compositor to render using this buffer (if it doesn't the surface is unmapped and nothing is displayed.

It's unclear to me if this behavior is supposed to be allowed by the protocol. It is possible for compositors to support it at a technical level, but neither Weston or Mir do currently (I ran into this trying to add lock screen support to Mir). I think it would be best to not destroy the buffer until after it has been committed.

This issue was introduced in 1d3e62c67f07a180fca02a6df1cf9648f2b50349, and has not yet been present in a release.

**Comment by emersion** [comment]
Right, my understanding of the spec is that clients are allowed to destroy buffers after `wl_surface.attach`, but I think many compositors don't support that...

**Comment by wmww** [comment]
This wasn't obvious to me from reading the spec, and Weston doesn't support it. Is there any particular wording in the spec or other source you can point to that says that's allowed?
