### ISSUE TITLE
AA is not working in RRGGBBAA

### ISSUE THREAD

**Issue by pati-ni** [swaywm/swaylock#303]
When I try the aa option it does not have the desired effect of increasing the alpha (or transparency).

`swaylock -c ffffff00` <- This turns my screen black

`swaylock -c ffffffff` <- This turns my screen white

This behavior has been like this for a long time..

**Comment by emersion** [comment]
This is by design. The Wayland compositor will not draw windows underneath the lockscreen, because that's a security issue.

**Comment by pati-ni** [comment]
Can I ask what is the security issue besides being able to peek at my underlying screen?

**Comment by emersion** [comment]
You've described the security issue.

**Comment by kennylevinsen** [comment]
To clarify, revealing user content while in a locked state is considered a security issue, and content other than the lock screen is therefore not rendered. Transparency works, there is just nothing to reveal.

**Comment by pati-ni** [comment]
Okay, I see. In that case, it should be more clear in the docs that there is an implicit black box behind everything. IMO, alpha option given this design is a bit confusing.
