### ISSUE TITLE
Feature to allow unlocking via command

### ISSUE THREAD

**Issue by discapes** [swaywm/swaylock#308]
Hi! It would be nice if it was possible to unlock swaylock programmatically. For example, I can unlock i3lock simply with `pkill i3lock`. If I try the same with swaylock, I get a red screen. This would enable users to add more unlock methods easily that pam might not support. Couple of use cases:
1. Killing swaylock when resuming from hibernation, if the user already has full-disk encryption
2. Killing swaylock when a fingerprint is detected.

**Comment by emersion** [comment]
You should be able to `pkill -USR1 swaylock`.

**Comment by discapes** [comment]
Yes, thank you. I should RTFM
