### ISSUE TITLE
Immediate relaunch

### ISSUE THREAD

**Issue by hholst80** [swaywm/swaylock#315]
I enter my password.  I can see the screen for a glimps.  And then swaylock nagscreen is back.  I have to randomly enter my correct password up to 10 times before swaylock finally gives up and does not restart it.

Happy to debug this.   This is *very* consistent on multiple machines.

Relevant parts of my sway config:

```
exec --no-startup-id swayidle -w timeout 600 'swaylock -i .config/sway/bg.jpg'
```

**Comment by kennylevinsen** [comment]
swaylock unlocks just before it exits, so if it appears again it is because something is running it again.

> exec --no-startup-id swayidle -w timeout 600 'swaylock -i .config/sway/bg.jpg'

Pass `-f` to swaylock to have it daemonize after locking instead of blocking swayidle until unlock.

**Comment by hholst80** [comment]
meaning this should work?

```
exec --no-startup-id swayidle -w timeout 600 'swaylock -f -i .config/sway/bg.jpg'
```

**Comment by kennylevinsen** [comment]
Possibly.

**Comment by emersion** [comment]
Closing because this doesn't seem like a swaylock bug.
