### ISSUE TITLE
Output on/off

### ISSUE THREAD

**Issue by fadri14** [swaywm/swaylock#316]
Hello,

Sorry, I know this is the bug section but I can't find where to ask for help.

When I activate swaylock, my screen turns off and as soon as I press a key, it turns back on.

Thanks to anyone who takes the time to help me.

**Comment by kennylevinsen** [comment]
> Sorry, I know this is the bug section but I can't find where to ask for help.

Same as sway, #sway on irc.libera.chat.

> When I activate swaylock, my screen turns off and as soon as I press a key, it turns back on.

This is not a question, and swaylock does not turn monitors on or off. People tend to use e.g. swayidle for that. You can ask in the chat for more information.

**Comment by fadri14** [comment]
Sorry, I didn't know there were discussions in irc.

Could you please tell me how to join.

I don't know what sway's chat channel is.

**Comment by fadri14** [comment]
I just figured out how to do it. Sorry for the inconvenience
