### ISSUE TITLE
Cursor only disappears once moved.

### ISSUE THREAD

**Issue by c-edw** [swaywm/swaylock#32]
This is really minor. As long as you don't move your cursor after activating swaylock, the cursor will stay on screen. Once you do move your cursor, it will disappear (and on a sidenote, it does a strange movement before disappearing, kind of like a slide-fade into the bottom right corner... perhaps intended?).

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/sway/issues/3080
