### ISSUE TITLE
CRITICAL SECURITY ISSUE: Unlock when connecting external monitor

### ISSUE THREAD

**Issue by adityakrcodes** [swaywm/swaylock#322]
It unlocks automatically when connecting to an external monitor through HDMI port.

* How to reproduce?
Lock your machine with swaylock then connect an external monitor through HDMI, it will unlock the swalock.

I am using Arch with Hyprland.

**I think this could be very critical issue for people like me who uses laptop as there primary device and work from anywhere, anyone can connect on HDMI cable to unlock the machine**

**Comment by emersion** [comment]
Most likely an Hyprland bug.
