### ISSUE TITLE
Swaylock using 940% of CPU

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [swaywm/swaylock#328]
![image](https://github.com/swaywm/swaylock/assets/76522725/a3906e4d-e195-4d5d-bd68-6dde0f0ff257)

System becomes extremely laggy and cant figure out what to do

I am using arch , hyprland with swaylock, nothing fancy, just added 
```exec-once = swayidle -w timeout 300 'swaylock' timeout 600 'hyprctl dispatch dpms off' timeout 1200 "systemctl suspend"  timeout 1800 "systemctl hibernate" before-sleep 'swaylock' ``` 
in hyprland.conf

any way to tackle this issue? ready to provide any info regarding this.

**Comment by kennylevinsen** [comment]
These are threads, and swaylock does not start any on its own. Please confirm that this is upstream swaylock, and not a fork with effects such as blurring.

If this is upstream swaylock, it might be a broken PAM module - e.g. fingerprint reader integration.

**Comment by piush-terminalwitchcraft** [comment]
yeah, its a fork of swaylock, sorry for posting here. I use swaylock-effects-git
