### ISSUE TITLE
[bug] hyprland swaylock

### ISSUE THREAD

**Issue by rimarien** [swaywm/swaylock#329]
i'm getting the following error on swaylock version 0176ddb (Nov  2 2023, branch 'master')

```[main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely```

**Comment by emersion** [comment]
0176ddb is not a swaylock version. Moreover, if a protocol is missing, it's a compositor issue, not a swaylock issue. input-inhibitor support has been removed from swaylock.

**Comment by RyanOrigens** [comment]
it happens on hyprland 33.1, i'm unsure how to get it fixed....

**Comment by kennylevinsen** [comment]
Step one, use a real swaylock version or file a bug against your fork of choice. The OP did not use a any version of swaylock - likely a fork with effects - so this is not the right place to ask about issues.

swaylock no longer uses input inhibition so this message and issue would not occur with it.
