### ISSUE TITLE
[feature-request] Would it be possible to add the current time in the middle of circle or the current username

### ISSUE THREAD

**Issue by mxaddict** [swaywm/swaylock#334]
I don't know if this is already supported or not, but would it be possible to add the current time/clock or the current logged in username in the middle of the screen?

If it's possible I've not been able to find it in the docs/help text

**Comment by mxaddict** [comment]
> There is a fork of `swaylock` called `swaylock-effects`, which supports time display with the `--clock` option, and with its `--indicator-image` option and some work you could make it display extra text like the username. `swaylock-effects` proper is not currently maintained, although it does have a recursive fork at https://github.com/jirutka/swaylock-effects , which has a recent release (but, as far as I'm aware, no guarantees of future feature updates.)

I think both of those are unmaintained.

Would it make sense to create a PR to add a feature like that to main `swaylock` repo?

Cause if could work on a PR if we can get it merged here, as I'd love to use just the main swaylock with such a feature! ❤️

**Comment by emersion** [comment]
Sorry, but we want to keep swaylock simple.

**Comment by mxaddict** [comment]
> Sorry, but we want to keep swaylock simple.

I see 😿

**Comment by cunlem** [comment]
Without username or VT number displayed it's hard to tell which session I'm unlocking. It would be useful if swaylock could e.g. display externally provided info text.
