### ISSUE TITLE
Screencopy failed on hyprland dpms on

### ISSUE THREAD

**Issue by hrasekj** [swaywm/swaylock#338]
Hello i have swayidle configured to call `hyprctl dispatch dpms on` on timeout, which will turn off the monitors and swaylock to take a screenshot on lock event. But when screen is off, the swaylock ends with error `[main.c:626] Screencopy failed` and does not lock the screen.

Is this a bug, or I have miss configuration?

```bash
$lockCmd = bash $HOME/.config/hypr/scripts/screenlock.sh
swayidle timeout 330 '$lockCmd --with-grace' timeout 300 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 300 'playerctl pause' timeout 1800 'systemctl suspend' after-resume 'hyprctl dispatch dpms off' before-sleep '$lockCmd'
```

scripts/screenlock.sh
```bash
swaylock -e --color 000000 --fade-in 0.3 --grace $grace --grace-no-mouse --grace-no-touch --screenshots --effect-pixelate 4 --show-keyboard-layout --indicator --clock
```

**Comment by kennylevinsen** [comment]
swaylock does not use screencopy. You're likely using a fork, which we do not support. Open an issue with the fork instead.
