### ISSUE TITLE
Swaylock blocked and cannot interact with

### ISSUE THREAD

**Issue by Talleyrand-34** [swaywm/swaylock#344]
I don't know which info submit so if i do something wrong, please ask me to add.

I use nixos, hyprland and swaylock. When i suspend my laptop by bringing down the screen or have a external monitor connected through hdmi, when i want to input the password swaylock is frozen.

At first I would like a method to come around this problem like opening tty2 and reloading swaylock, or unlocking from tty2. I couldn find any resources about this.

Thank you very much for your attention

**Comment by TurtleMeds** [comment]
I have the same issue

**Comment by Cody-W-Tucker** [comment]
Similar to #124 and #217 the common link for them was Swayidle.

I'm also having the same problem on NixOS, hyprland, and swayidle. I'm going to research more on my side and share anything that could be helpful.

**Comment by M4he** [comment]
Same for me when using [swaylock-effects](https://github.com/jirutka/swaylock-effects/) with Hyprland on NixOS. There's an emergency recovery method for resetting swaylock that seems to work for me, see my comment here: https://github.com/hyprwm/Hyprland/issues/3581#issuecomment-1987363139

**Comment by justDeeevin** [comment]
> the common link for them was Swayidle

I'm having this same problem using hypridle.

**Comment by sachinchaudhary1808** [comment]
same issue i experinaced today..

**Comment by kennylevinsen** [comment]
> Same for me when using [swaylock-effects](https://github.com/jirutka/swaylock-effects/) with Hyprland.

This is not `swaylock-effects`.

---

I have good reason to believe that these are all Hyprland focus bugs, especially as the linked issue says it also happens with Hyprlock. Refocus logic can be a bit tricky to get right at times, so I'm not too surprised - just not swaylock's fault so closing.

Can be reopened if discovered on sway or if the issues on the Hyprland tracker is fixed and swaylock still doesn't work afterwards.
