### ISSUE TITLE
Missing ext-session-lock-v1

### ISSUE THREAD

**Issue by teclab-at** [swaywm/swaylock#348]
Dear swaylock Team,

I am on Debian 12.5 Bookworm. 
`wayland-protocols` is 1.31-1
All needed dependencies installed: `libwayland-dev libxkbcommon-dev wayland-protocols libgdk-pixbuf2.0-dev libpam0g-dev fish`
`ext-session-lock` is in `/usr/share/wayland-protocols/staging/`

Everything compiles fine, but when running I get:
`[main.c:1233] Missing ext-session-lock-v1`

I was under the impression that installing the `wayland-protocols` should be enough. Obviously not.
What am I doing wrong? Or might this be a bug?

Could you please support?

Thank You!

**Comment by teclab-at** [comment]
Can you please recommend another window manager?

**Comment by teclab-at** [comment]
The compositor is gnome-shell:
```
Display: wayland server: X.Org v: 1.22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell v: 43.9 driver: dri: swrast gpu: vmwgfx

```

**Comment by kennylevinsen** [comment]
GNOME does not implement the session lock protocol, and uses its own internal locking mechanism.
