### ISSUE TITLE
the config file does not work after the update

### ISSUE THREAD

**Issue by Dolbaeb777K** [swaywm/swaylock#349]
I am using the Hyprland JaKooLit config in the openSUSE Tumbleweed distro. Everything used to work for me: a circle in the center, time, etc.
But after distro's updating with `sudo zypper dup` suddenly `swaylock` stopped working normally. When turned on: a white screen, and when you press the keys, a circle appears in the center.

After finding information about how swaylock works on archwiki, I wrote the command swaylock --config /home/hip/.config/swaylock/ in the terminal, but nothing happened. However, with sudo I got this error:
```
 hip@192  ~  sudo swaylock --config /home/hip/.config/swaylock/
[sudo] пароль для root: 
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
2024-03-26 16:50:32 - [main.c:1242] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.
 ✘ hip@192  ~  
```
I tried to use this path ` /home/hip/.config/swaylock/config` or `$HOME/hip/.config/swaylock/config` etc. but the help for using swaylock options popped up. Sorry about stupid Issue, I am a new in linux)

**Comment by kennylevinsen** [comment]
(Also, the config argument must point to the config *file*, not the directory.)

**Comment by Dolbaeb777K** [comment]
Okay, thx! Idk about fork) I'll find out more about fork)
