### ISSUE TITLE
[Feature Request] icon overlay on lock screen similar to `13lockr`

### ISSUE THREAD

**Issue by pfr-dev** [swaywm/swaylock#354]
I've only recently started using Wayland and have installed `swaylock`. On X I used [i3lockr](https://github.com/owenthewizard/i3lockr) which is a fork of `i3lock` which adds some extra features. Namely, the ability to put an icon or png overlay on the lockscreen with a `-i` flag (as well as distortion blur). I think this is neat and wondered if you'd be willing to add this to `swaylock`?

**Comment by emersion** [comment]
Sorry, we're not interested in expanding the scope of swaylock at this time. There are swaylock forks and alternatives that offer more features.
