### ISSUE TITLE
Error in Hyprland. swaylock: ../swaylock-1.7.2/main.c:414: join_args: Assertion `argc > 0' failed.

### ISSUE THREAD

**Issue by hadishahpuri** [swaywm/swaylock#360]
Hello
I'm facing this error in Hyprland:
swaylock: ../swaylock-1.7.2/main.c:414: join_args: Assertion `argc > 0' failed.

EndeavourOS
Hyprland: v0.40.0, commits: 4606

**Comment by kennylevinsen** [comment]
What swaylock command-line and/or config file have you used? You're failing on parsing the image path argument, so maybe you're just not specifying a valid one.

**Comment by hadishahpuri** [comment]
My bad!!!
Yap.. the image file was updated every hour and was corrupted
