### ISSUE TITLE
anyway to execute a command after swaylock triggers using swaylock config

### ISSUE THREAD

**Issue by sachinchaudhary1808** [swaywm/swaylock#367]
is there any way to execute a command after swaylock executes like ``` playerctl pause ```
inside swaylock config

**Comment by emersion** [comment]
No, there is no way to do this with the swaylock config, and I don't think it makes sense to add one. You can invoke any command you want alongside swaylock, e.g. `swaylock & other-command` in the Sway config file.

**Comment by sachinchaudhary1808** [comment]
> No, there is no way to do this with the swaylock config, and I don't think it makes sense to add one. You can invoke any command you want alongside swaylock, e.g. `swaylock & other-command` in the Sway config file.

Yeah we can achieve that.

I use logind config that does not suspend my laptop when lid is closed and external power is connected, so my music was playing, i wanted to stop that..

I know i can do this with some configuration, but it's a little more work then just simply putting something in sway lock configuration...

Thanks
