### ISSUE TITLE
swaylock after swayidle does `dpms off` and starts swaylock causes system to freeze when swayidle invokes `dpms on` for resume

### ISSUE THREAD

**Issue by Stephen-Seo** [swaywm/swaylock#370]
I'm not sure where the right place for this issue is, but here's the details.

On ArchLinux with `sway`, `wlroots`, `swayidle`, and `swaylock` packages in the official repositories, there is no issue.

But if `sway-git` and `wlroots-git` is installed from the AUR, the swaylock instance started by swayidle causes a system freeze on resume when swayidle does `dpms on` on resume. The system becomes unresponsive, one cannot switch to another tty, and the power button is ignored when by default it should shutdown the system.

Note I also have `libdisplay-info-git` and `xorg-xserver-git` installed from AUR as well, which is built before I build `wlroots-git`.

I have tried `swaylock-git` and `swayidle-git` and the issue still occurs with `sway-git`.

Nothing is logged to systemd-journald, and the output of sway also does not have any logs when the freeze occurs.

My swayidle command is this:

    exec swayidle -w \
             timeout 780 'swaylock -f -c 007050 -i /usr/share/backgrounds/archlinux/geolanes.png' \
             timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
             before-sleep 'swaylock -f -c 007050 -i /usr/share/backgrounds/archlinux/geolanes.png'

**Comment by Stephen-Seo** [comment]
I've been doing some testing with this issue, and tried running `sway -V` and `swayidle -d`. What shows up when sway's stdout and stderr is piped into a file after a freeze is this:

    Aug 04 15:05:47 2024-08-04 15:05:47 - [Line 650] idle state
    Aug 04 15:05:47 2024-08-04 15:05:47 - [Line 146] Cmd exec swaylock -f -c 007050 -i /usr/share/backgrounds/archlinux/geolanes.png
    Aug 04 15:05:47 2024-08-04 15:05:47 - [Line 172] Spawned process swaylock -f -c 007050 -i /usr/share/backgrounds/archlinux/geolanes.png
    Aug 04 15:05:47 2024-08-04 15:05:47 - [Line 174] Blocking until process exits
    Aug 04 15:05:47 2024-08-04 15:05:47 - [Line 179] Process exit status: 0
    Aug 04 15:05:49 00:02:47.218 [INFO] [wlr] [backend/drm/drm.c:1672] Scanning DRM connector 128 on /dev/dri/card1
    Aug 04 15:05:49 00:02:47.218 [INFO] [wlr] [backend/drm/drm.c:1759] 'DP-3' disconnected
    Aug 04 15:05:49 00:02:48.032 [INFO] [wlr] [backend/drm/drm.c:1672] Scanning DRM connector 128 on /dev/dri/card1
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1751] 'DP-3' connected
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1555] Detected modes:
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1585]   1920x1080 @ 60.000 Hz (preferred)
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1585]   1920x1080 @ 74.973 Hz 
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1585]   1920x1080 @ 60.000 Hz 
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1585]   1920x1080 @ 59.940 Hz 
    ...
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1605] Physical size: 600x340
    Aug 04 15:05:49 00:02:48.036 [INFO] [wlr] [backend/drm/drm.c:1787] connector DP-3: Requesting modeset

(My timezone is KST or UTC+9.)

Also, apparently "waking from idle" with mouse doesn't cause a freeze, but pressing backspace to "wake from idle" freezes up the system.

**Comment by gonzalobf** [comment]
Same problem here. As you said, I get the same behavior when compiling latest `sway` version and using `swaylock` from AUR. I needed to disable swaylock for now.

**Comment by kennylevinsen** [comment]
> and the power button is ignored when by default it should shutdown the system.

Unless you bound the power button in sway, such behavior would be done by `systemd-logind` if configured to react to the power button.

`systemd-logind` eavesdrops on keys on its own. sway freezing cannot be to blame for that (sway and swaylock never set any inhibitors, and swayidle only sets suspend inhibitors).

Not being able to switch VT could indicate that sway is still running but unresponsive, but if things outside sway doesn't work it could indicate e.g. a kernel panic or other such external lock-up.

> I've been doing some testing with this issue, and tried running sway -V and swayidle -d.

The debug logging flags are:
- `sway -d` (`-V` only gives you the INFO loglevel which is nowhere near as detailed as debug)
- `swayidle -d`
- `swaylock -d`

> What shows up when sway's stdout and stderr is piped into a file after a freeze is this:

Please don't snip the logs, as one then has to guess if anything important could have happened.

**Comment by kennylevinsen** [comment]
After dpms on, there's a bunch of udev events about the monitors glitching in and out (pretty common when monitors leave power save states unfortunately), but at `20:34:47`, DP-1, DP-2 and DP-3 are on and ready from sway's perspective. Input processing should also work just fine.

Try to see if disconnecting a monitor and reconnecting it physically causes something to appear. Maybe the GPU/driver has bugged out - I have experiences cases where amdgpu reports A-OK but nothing is on screen a few times.

**Comment by Stephen-Seo** [comment]
The thing is, this bug has never occurred to me when using the current release of `sway`, and only with `sway-git` (and friends). So I suspect some implementation change in between is causing this. I don't think bisecting is feasible since `sway-git` chases changes in `wlroots-git`, and will be a bit of a headache to ensure both versions are valid during a bisection.. It can probably be done in a full day but not looking forward to trying when the bug is not easily reproducible.

**Comment by kennylevinsen** [comment]
I'd still ask you to see what happens when you disconnect a monitor and reconnect it after the incident. The log contains no failures or reasons to suspect a freeze, and your GPU driver accepted the content we're submitting so it's the driver + GPU's responsibility to present it to you. Disconnect will show if sway is still responsive, show what happens when the display configuration is changed, and is an easy test.

For bisect, you can just use the sway commit date to get a matching wlroots commit:

```sh
# If in your reflog
git checkout 'master@{1979-02-26 18:30:00}'
# Otherwise
git checkout `git rev-list -n 1 --first-parent --before="1979-02-26 18:30" master`
```

When building wlroots as a subproject, building a sway version for testing becomes pretty easy.

**Comment by Stephen-Seo** [comment]
Sorry for the late reply, here is the [output of `sway -d` when a monitor is disconnected and reconnected](https://gist.github.com/Stephen-Seo/88f524a1341b58ba4f135ef18dae07d3).

I may do the git bisect soon.

**Comment by kennylevinsen** [comment]
The log does not seem to contain a reproduction of an issue, but just starting sway and 20 seconds later disconnecting then reconnecting a display. The logs are only useful if they are from a run reproducing the issue.

**Comment by kennylevinsen** [comment]
All debug logs must be from sessions that reproduced the issue as we are trying to understand what happens. A "good" debug log is very rarely interesting on its own, and mainly serves as a point of comparison with a "bad" debug log to make it easy to single out any differences that could be attributed as cause.

Everything so far has been based on the assumption that all the debug logs you share were collected from sessions that reproduced the problem. The request to reconnect the monitor was to validate how sway reacted seeing that your shared logs showed no sign of issues with sway still seeming responsive, so if that had been a session with the reproduced issue, trying to see if sway would react to a display hotplug is a logical next step. There is nothing interesting about hotplugging when things are working fine.

Only when you have a reasonably stable (even if slow) reproduction would you be able to attempt a bisect for a theoretical bad commit, but even if a bad commit is found we'd still need debug logs from the system in that state and might need you to do some tests (such as reconnecting monitors) as it's not guaranteed that it's externally reproducible.

**Comment by Stephen-Seo** [comment]
Then we are in agreement that the bug needs to be reproducible to be able to figure it out (from logs and behavior) and fix it.

> Please don't snip the logs, as one then has to guess if anything important could have happened.

From this I thought that all logs were important, but it seems that isn't the case. As stated earlier, I will continue to keep tabs on my system to see if the freeze bug occurs again, and to hopefully figure it out to fix it if it does.

**Comment by Stephen-Seo** [comment]
I'm throwing in the towel on my `git bisect` attempts. I decided to git-bisect today because I encountered the freeze bug again without anything useful in the logs. Finding a "matching" wlroots-git commit to build off of went well as I did as you suggested with `git rev-list ...`. There were some compilation issues which were solved by resolving "matching" enums that were separately defined enums with the same meaning passed to a function that expected the other enum.

But during the bisect process, sway commits `0b84d82b9aad05010479140774ac5ee1fea8ea97` and `2867ef646b67138a796b7d5ae46428c255cc928f` would not run. I did build them with the respective wlroots commits. I'm guessing some dependency may need downgrading, and I feel like with so many moving parts with sway, I don't think it's feasible to continue. The log for attempting to run sway with one of the "fail-to-launch" [builds is here if you're interested](https://gist.github.com/Stephen-Seo/14ff0906426df6cc354240aad0ee1d9c). I think for now I'll stick to `sway` instead of `sway-git` because with so many moving parts, sway seems to be difficult to git-bisect. Seems to be a problem mentioned here https://github.com/swaywm/sway/issues/7441 .

**Comment by kennylevinsen** [comment]
>  I decided to git-bisect today because I encountered the freeze bug again without anything useful in the logs. 

Still, please share the logs. In particular, focus on figuring out whether your whole system is frozen (which would be a kernel bug, and not sway's fault even if what sway does triggers it) or if just sway is frozen is important, as well as how frozen sway is (e.g., hotplug monitors and keyboards).

Doing a few tests on a single reproduction is a lot easier than getting repeated, stable reproductions for bisection. Otherwise it is very hard to know if a commit is truly good or if you simply haven't hit the issue on it yet.

> But during the bisect process, sway commits 0b84d82b9aad05010479140774ac5ee1fea8ea97 and 2867ef646b67138a796b7d5ae46428c255cc928f would not run.

You just do `git bisect skip` to skip commits that cannot be tested. When building arbitrary commits, it's a given that you will occasionally end up on one that is too buggy or otherwise not worth testing. That goes for any project.

There definitely aren't "so many moving parts" - there is 1 moving part that needs to be kept in sync.

> for now I'll stick to sway instead of sway-git 

Note that a sway release isn't too far into the future, at which point sway effectively becomes sway-git.

**Comment by Stephen-Seo** [comment]
> Still, please share the logs. In particular, focus on figuring out whether your whole system is frozen (which would be a kernel bug, and not sway's fault even if what sway does triggers it) or if just sway is frozen is important, as well as how frozen sway is (e.g., hotplug monitors and keyboards).

I have checked the logs at the time, and everything seems as normal until the time of the freeze, where nothing is logged until I force shutdown the computer (cannot switch tty, unresponsive to power switch). I think at this point, the logs I've already shared aren't that different looking over them myself.

> Doing a few tests on a single reproduction is a lot easier than getting repeated, stable reproductions for bisection. Otherwise it is very hard to know if a commit is truly good or if you simply haven't hit the issue on it yet.

I'm not quite sure what you mean here, may you please elaborate? My current workflow for testing has been triggering swayidle to do `dpms on` after monitors have turned off as that appears to be the only condition to cause the freeze bug.

> You just do git bisect skip to skip commits that cannot be tested. When building arbitrary commits, it's a given that you will occasionally end up on one that is too buggy or otherwise not worth testing. That goes for any project.

Actually, I used `git bisect skip`, and I decided to stop because I didn't want a large gap of skipped commits when I realized I could not run `sway-git` for inexplicable reasons (this different bug did not have anything useful in the logs either, and I shared the logs of one such instance of `sway-git` refusing to start).

> There definitely aren't "so many moving parts" - there is 1 moving part that needs to be kept in sync.

The existence of the other bug where `sway-git` does not run makes me think there are more "moving parts", and I don't think merely keeping "contemporarily up to date" with `wlroots` will fix it.

> Note that a sway release isn't too far into the future, at which point sway effectively becomes sway-git.

Noted.

To be honest, I have been avoiding sway for a bit now since this bug has been disheartening to me. When I have time this week, I may or may not try to do a `git bisect` again. But as mentioned in the other issue on the Github Issues page for `sway` that I linked in my last reply, `git bisect` doesn't seem to be a feasable thing, based on what was discussed there and what I've personally experienced.

**Comment by kennylevinsen** [comment]
> I have checked the logs at the time

Always share the full logs rather than just your own conclusion.

> I'm not quite sure what you mean here, may you please elaborate? My current workflow for testing has been triggering swayidle to do dpms on after monitors have turned off as that appears to be the only condition to cause the freeze bug.

My point is that you cannot do a bisect unless your reproduction is so good that you can know for sure if the bug is present or not. For example, if the issue happens *every* time you dpms off without exception, then it is stable. If it takes 10 or 20 dpms off to reproduce, it is *not* stable - even if you dpms off 20 times without issue, the problem could just happen on the 21st attempt, and so it becomes very difficult to know if a commit is *good* or just slower to reproduce the issue than average.

On the other hand, there's plenty of things to look for just with a single reproduction regardless of stability. For example:

1. If after the freeze sway still reacts to hotplug events (e.g., showing gpu changes or inputs showing up), then sway is still alive but stuff just isn't on your screen
2. If sway does not react, but your system journal/dmesg does (e.g., showing USB changes), then sway might be stuck while your kernel is fine. In this case, SysRq sequences should also let you escape to a VT.
3. If your journal is also completely silent no matter what you do, then it might be your kernel having panicked (which is *always* and without exception a kernel bug, even if caused by a sway/wlroots change).
4. If alive, ssh'ing into a system can see if sway is stuck in a CPU-burning loop, and attaching a debugger can say where.

It makes sense to do all this *before* a bisection because it's far easier and can be done any time the issue occurs, and some of the outcomes even rule out that the issue is in sway, making a bisection of sway somewhat irrelevant.

> The existence of the other bug where sway-git does not run makes me think there are more "moving parts",

None that are relevant to your bisect. There are other dependencies (libxkbcommon, mesa, ...), but they're using the same version as your release version of sway not to mention every Wayland client, so it's somewhat unlikely that they're the cause of issues if your old sway version works fine.

In either case, having a high confidence last good commit and first bad commit is the most important thing, as it lets us focus on just that range rather than the over 500 commits between wlroots 0.17.x and master. That's true even if there are several untested commits in the range.

> To be honest, I have been avoiding sway for a bit now since this bug has been disheartening to me. When I have time this week, I may or may not try to do a git bisect again.

Sorry to hear that - we're here to help, but we need detailed information from people reproducing the issue to have a chance of finding it, if it's even in sway.

**Comment by Stephen-Seo** [comment]
> Always share the full logs rather than just your own conclusion.

Ok, I'll do so next time. It just seems pedantic to post a really long list of logs to gist.

> My point is that you cannot do a bisect unless your reproduction is so good that you can know for sure if the bug is present or not. For example, if the issue happens every time you dpms off without exception, then it is stable. If it takes 10 or 20 dpms off to reproduce, it is not stable - even if you dpms off 20 times without issue, the problem could just happen on the 21st attempt, and so it becomes very difficult to know if a commit is good or just slower to reproduce the issue than average.

Ok that makes sense. It is unfortunately difficult to reproduce the freeze bug reliably.

About your notes about troubleshooting the freeze: using SysRq and ssh were two things I didn't think to try, so I'll try them next time. The first three problems did occur so perhaps it may be kernel related.

> It makes sense to do all this before a bisection because it's far easier and can be done any time the issue occurs, and some of the outcomes even rule out that the issue is in sway, making a bisection of sway somewhat irrelevant.

True, I'll keep this in mind next time I try troubleshooting the freeze.

> None that are relevant to your bisect. There are other dependencies (libxkbcommon, mesa, ...), but they're using the same version as your release version of sway not to mention every Wayland client, so it's somewhat unlikely that they're the cause of issues if your old sway version works fine.

Ok, then I'll take your word for it, I just am not too familiar with `sway-git` and friends myself.

> In either case, having a high confidence last good commit and first bad commit is the most important thing, as it lets us focus on just that range rather than the over 500 commits between wlroots 0.17.x and master. That's true even if there are several untested commits in the range.

True, I'll be more thorough next time (if I do try another `git bisect` attempt).

Your SysRq and ssh ideas are intriguing, so I will make another attempt at troubleshooting soon. Hopefully the ideas will work, otherwise I don't think there are more avenues to try to troubleshoot the freeze.

**Comment by kennylevinsen** [comment]
> Swaylock can still be unlocked blindly, 

Hmm, so that would be swaylock not rendering, or e.g. sway messing up and not sending frame callbacks to the lock surface causing swaylock to stall.

**Comment by stromnet** [comment]
> I have the similar problem when using swayidle-git([swaywm/swayidle@49d200e](https://github.com/swaywm/swayidle/commit/49d200eeb4710e377a4677aaedd66d9a73532814)) sway-git([swaywm/sway@28fd735](https://github.com/swaywm/sway/commit/28fd73589df0e73e1d15e165acd90651a5f805d6)) swaylock-git([b70d85e](https://github.com/swaywm/swaylock/commit/b70d85ec145520ba3ebaa4c51921a2761bc0c7f0)).

I have the exact same symptoms as described in this post, but with `sway-git 1.10.r7371.28fd735-1` + `wlroots-git 0.18.0.r7117.59138460c-1` together with `swayidle 1.8.0-2`  and `swaylock 1.7.2-2`  (Arch packages).

I can reproduce it on two laptops and one desktop. Mostly/only occurs when external displays are plugged in though, I think. Typically something like this is logged:
``` Aug 23 10:28:33 johan-amd sway[4715]: 698:46:56.207 [ERROR] [wlr] [backend/drm/atomic.c:79] connector HDMI-A-1: Atomic commit failed: Device or resource busy
Aug 23 10:28:33 johan-amd sway[4715]: 698:46:56.207 [ERROR] [sway/desktop/output.c:273] Page-flip failed on output HDMI-A-1
```

This started occurring for me after upgrading from `sway-git 1.10.r7315.5a7477c-1` & `wlroots-git 0.18.0.r6994.2f3ea4590-1` to the ones now in use (a few weeks ago)

Have not had the chance to play with debug logs etc, and not tested newer builds yet.
