### ISSUE TITLE
Swaylock unlocks immediately after locking when using `--grace`

### ISSUE THREAD

**Issue by Narcha** [swaywm/swaylock#378]
Running `swaylock --grace 5` opens Swaylock, which then closes itself after a few milliseconds.

Without the `--grace` option set, it works as intended.

I could not find any input events that could cause this to happen:
- Running `libinput debug-events` shows no unexpected touchpad or key events
- Running something like `sleep 5; swaylock --grace 5` also exhibits this behavior. Thus, the return key being pressed to run the command is also not the culprit.

<details><summary>My setup</summary>
<p>

- OS: Arch Linux
- `swaylock --version`: `swaylock version v1.7.0.0-1-g496059a (" __DATE__ ", branch 'master')`
- WM: Hyprland 0.43.0

</p>
</details>

**Comment by emersion** [comment]
`--grace` is not a swaylock option.

**Comment by Narcha** [comment]
Apologies, I forgot I was using a fork
