### ISSUE TITLE
"Eye candy" options: clock, indicator position?

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/swaylock#38]
Hi, I'm loving using Sway and Wayland so far! I've got some high hopes for the future.

It looks like there aren't options for a clock or a date to be displayed on the lock screen. I was wondering if there are plans to add these features to swaylock. I was using i3lock-color before switching to Sway, and I loved the ability to show a clock and date in one corner while setting the indicator to display in another corner.

**Comment by ddevault** [comment]
Similar to i3lock-color's situation with upstream i3, we are not interested in tricking out swaylock with eye candy. However, again similar to i3lock-color, I encourage you to fork swaylock for your own needs.
