### ISSUE TITLE
swaylock automatically unlocks from sleep when a key is held

### ISSUE THREAD

**Issue by vandabbin** [swaywm/swaylock#388]
Hi! Perhaps there is something in the configuration I am missing but when I wake my system from sleep it is locked and i can unlock with password. If i wake the machine while holding any key on the keyboard however, the lockscreen is bypassed and i don't need to enter a password. I can provide any additional information needed

**Comment by kennylevinsen** [comment]
If you're running the latest releases of sway and swaylock (and *not* a fork), then the lock screen will only go away if swaylock explicitly requests unlock, which it only does on PAM success, and PAM authentication is only attempted on "enter". swaylock will not attempt to unlock on a random keypress, and even if swaylock crashes the session will not be unlocked.

Maybe you have something in your PAM config that causes an empty password to be approved?

**Comment by vandabbin** [comment]
Maybe. I noticed this while testing out Manjaro Sway. I haven't modified any settings so it's in their stock configuration. Perhaps the issue is something they did

**Comment by mstoeckl** [comment]
> I noticed this while testing out Manjaro Sway. I haven't modified any settings so it's in their stock configuration. Perhaps the issue is something they did

The stock configuration uses swaylock-effects, not swaylock. (See https://github.com/manjaro-sway/iso-profiles/blob/1ae58cbd5afee59a16b22c17b8aaa6e1f17dd35b/community/sway/Packages-Desktop#L11; swaylock-effects is listed in the [full iso package list](https://mirror.manjaro-sway.download/manjaro-sway/manjaro-sway-24.1.1-241110-linux66.iso.pkgs).)

**Comment by vandabbin** [comment]
Thanks. Sorry about that!
