### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jubalh** [swaywm/swaylock#44]
I wanted to inquire whether you plan a new release for swaylock (and swayidle).

As I understand it the last stable version of sway included these programs. But with sway 1.0 this is going to be changed and they are seperate.

If this is the case I suggest creating new releases for swaylock and swayidle when releasing sway 1.0.

Latest release of swaylock for example doesn't even build for me because of a wrong [include path](https://github.com/swaywm/swaylock/commit/f801164b9f9d83ba28e7c60b3089691e3222a7c6). I fixed this for our local package but having everthing in order when sway 1.0 gets out would be nice.

I would also suggest to set a version automatically instead of needing to pass them at build time.
So in case git is not present just use that version. If git is present use version + git hash or whatever.

**Comment by ddevault** [comment]
Let me go ahead and do a release now, actually...

**Comment by jubalh** [comment]
@ddevault thanks! Edited above message just before I saw your reply. Please read again regarding version.

**Comment by ddevault** [comment]
I'll tag a release now under the normal release flow but if you want to change how the version is stored, you should write a patch.

**Comment by ddevault** [comment]
swaylock 1.3 is now available:

https://github.com/swaywm/swaylock/releases/tag/1.3
