### ISSUE TITLE
swaylock 1.3 build failure

### ISSUE THREAD

**Issue by jubalh** [swaywm/swaylock#46]
If I don't have wlroots as a build dependency I get:

```
meson.build:38:0: ERROR:  Dependency "wayland-client" not found, tried pkgconfig
```

Should https://github.com/swaywm/swaylock/commit/56b672a16c248c268fde17243a914a3bcfa4ac47 have removed `wayland_client = dependency('wayland-client')` or does it need wlroots/sway installed to build?

**Comment by ddevault** [comment]
Given that swaylock is a Wayland client, do you suppose it might be natural for it to require wayland-client?

**Comment by emersion** [comment]
You need libwayland, it's also a dependency of wlroots.
