### ISSUE TITLE
[Doc] turn off dpms on lock/turn on dpms on action

### ISSUE THREAD

**Issue by piu130** [swaywm/swaylock#49]
The i3 man page provides this nice script to turn off dpms on `i3lock` and turn on dpms on action.

```bash
#!/bin/sh
revert() {
  xset dpms 0 0 0
}
trap revert SIGHUP SIGINT SIGTERM
xset +dpms dpms 5 5 5
i3lock -n
revert
```

We should document this in the README or elsewhere too. It would look something like:

```bash
#!/bin/sh
revert() {
  swaymsg "output * dpms on"
}
trap revert SIGHUP SIGINT SIGTERM # How to fix this line?
swaymsg "output * dpms off"
swaylock
revert
```

But the `trap` command does not work. The dpms is off until the screen is unlocked (revert on last line).
What would be the wayland/wlroots equivalent for `trap`?

**Comment by emersion** [comment]
`trap` is a shell builtin, it doesn't matter whether it's X11 or Wayland.

Though, `xset dpms` manages the timeout to enable DPMS. The Wayland equivalent would be `swayidle`.

**Comment by piu130** [comment]
Sorry I just switched to sway recently. Would this script look like this:

```bash
# put task in background
swayidle \
    timeout 5 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' &
# lcok screen
swaylock -c000000
# kill last background task
kill %%
```
Or is there a better way to do this?

**Comment by KristerV** [comment]
A year later this is not in readme, and there is no wiki at all. Been trying for hours to get this to work, only now found this issue. Mind you Google also doesn't know any solutions. I say it's a good fit for readme as is a typical usecase. Or at least open the wiki.

@piu130's approach seems to be working, although also gives an error: `Failed to find session name: PID 2957 does not belong to any known session`.

Yet the trap command version doesn't integrate with swayidle. My purpose is to blank the screen immediately and then engage lock in 5 sec. So moving mouse too soon will cancel the locking also.

**Comment by piu130** [comment]
[Here](https://github.com/swaywm/swaylock/issues/99#issuecomment-546504901) is another solution to this problem.
