### ISSUE TITLE
RFE: Delay asking for a password

### ISSUE THREAD

**Issue by gdamjan** [swaywm/swaylock#50]
most screen lockers these days have an option to delay the password requirement, so that if your locker activates you have 2-3 seconds to just press a button and get your screen back without typing the password.

**Comment by emersion** [comment]
I bet this can be implemented with `swayidle`, or another client which would run `swaylock` after a timeout?

**Comment by gdamjan** [comment]
well if there was a passwordless swaylock that would work :)

or if there was a `swaymsg "output * blank-and-keyboard-locked on"` command ?

**Comment by emersion** [comment]
I'd like not to implement this in swaylock/sway, since this can be implemented by a third-party client.

**Comment by gdamjan** [comment]
> I'd like not to implement

would you be ok with someone else implementing it?

**Comment by emersion** [comment]
Clarification: I'd like not to have this in swaylock/sway, since this can be implemented by a third-party client.

This means you can write the third-party client. ;)

**Comment by gdamjan** [comment]
I think that option is suboptimal, and probably error prone, but _sigh_

**Comment by gdamjan** [comment]
https://github.com/gdamjan/swaylock/commit/c14d884b92d0f0ec695d89073e37a63b0513a732

there it is for anyone else

**Comment by steevel** [comment]
This should definitely be part of swaylock since we want to display (and abort) the actual lock screen. Feels like it would be a lot of work for a third party application to implement all of swaylocks display settings and render the exact same image before swaylock actually kicks in.

**Comment by emersion** [comment]
Nah, just open a layer shell surface that spawns swaylock after a timeout.

**Comment by drrossum** [comment]
> Nah, just open a layer shell surface that spawns swaylock after a timeout.

This sounds great. Can this easily be achieved with currently available tools?

**Comment by emersion** [comment]
Could be a pretty simple C program.

**Comment by edrex** [comment]
this should be default behavior imo not something users have to manually configure. the current behavior is a usability fail.

**Comment by ddevault** [comment]
As the maintainer of the project, I disagree and will not be enabling this behavior by default.

**Comment by gdamjan** [comment]
> As the maintainer of the project, I disagree and will not be enabling this behavior by default.

how about if it's optional? (my current branch has that)

**Comment by ddevault** [comment]
I don't really like it. I think that it would be worth having a more featureful fork of swaylock out there which is more open to including features like that.

**Comment by emersion** [comment]
I feel like we've already discussed about that, @gdamjan.

**Comment by mortie** [comment]
Sorry for resurrecting an ancient thread, but i think it's relevant (and, as #139 shows, people are still discussing it). I just merged gdamjan/swaylock:delay-password in to swaylock-effects: https://github.com/mortie/swaylock-effects/commit/c0f6b94f9f732429f23a8696578a1260c010ce13

**Comment by sh1boot** [comment]
So I copied something like the following out of /etc/sway.conf:
```
exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000'
```

After reading this thread I decided the simplest thing to do was changed it thus:
```
exec swayidle -w \
         timeout 270 'notify-send "getting sleepy"' \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000'
```

I'm sure that'll work fine.  I'm just too lazy to wait around to test it right now.

I think this works _better_ than a grace period.  If I see the notification then simply dismissing it is enough to reset the timeout, and in the mean time I can still see whatever I'm watching.  And if I don't see the notification then it really doesn't matter what happens next.

**Comment by mensinda** [comment]
I wrote a manager script for swayidle / swaylock that manually handles the logic: https://gist.github.com/mensinda/94d0b05604bbb50f9b5bd4a5f1b48bfb

After finishing this script, a friend told me that swaylock-effects has this feature [built in](https://github.com/mortie/swaylock-effects/blob/a863c2fd3c8b313f4d39ff03bcb8dad299727480/main.c#L1064-L1069)...
