### ISSUE TITLE
Force one keyboard layout

### ISSUE THREAD

**Issue by chzzzh** [swaywm/swaylock#55]
Seeing a layout is really nice addon, but 'd be nice to log in only entering a password without switching a layout. Pretty sure almost everyone got their keyword on a specific language.

xoxo to every contributor 🖤

**Comment by ddevault** [comment]
This seems unnecessarily tbh.

**Comment by chzzzh** [comment]
Still would be a nice addition anyway, instead of switching multiple layouts to enter a password.

**Comment by emersion** [comment]
I'd rather add a command to switch the current keyboard layout in sway. You could then run it right before locking.

**Comment by chzzzh** [comment]
Would be really nice, but there seems another issue with checking a keyboard layout (setxkbmap -query) on the wlroots side.

**Comment by emersion** [comment]
`setxkbmap` won't work. This would need to be a sway command.

**Comment by chzzzh** [comment]
It all references to `setxkbmap` support, as far as I see the situation, so then we just can set `setxkbmap` on both `before-sleep` and `after-resume` to have a special layout on unlock.

**Comment by emersion** [comment]
>setxkbmap won't work

(setxkbmap is a X11 tool, it doesn't work on Wayland)

**Comment by chzzzh** [comment]
Is an `setxkbmap` implementation planned?

**Comment by emersion** [comment]
>setxkbmap is a X11 tool, it doesn't work on Wayland

**Comment by chzzzh** [comment]
> > setxkbmap is a X11 tool, it doesn't work on Wayland

So how to change/lookup a keyboard layout from the terminal?

**Comment by emersion** [comment]
>I'd rather add a command to switch the current keyboard layout in sway.

**Comment by emersion** [comment]
Note that you can already completely change the layout with `swaymsg input '*' xkb_layout 'layout1,layout2'` like in the config. This new command would be to switch between layout1 and layout2.

**Comment by chzzzh** [comment]
`swaymsg input '*' xkb_layout 'ru'` doesn't change a layout at all.

**Comment by tindzk** [comment]
@ghost You can configure the keyboard layouts as follows in the Sway configuration:

```
input * xkb_layout  us,ru
input * xkb_variant us
```

To change the layout prior to `swaylock`, run this command:

```shell
swaymsg input '*' xkb_switch_layout 0
```
