### ISSUE TITLE
Not possible to chain commands after swaylock

### ISSUE THREAD

**Issue by Limero** [swaywm/swaylock#56]
Running the following command with i3lock will lock the screen and then suspend the computer, so the next time the computer is started you will be prompted for a password.
`i3lock && systemctl suspend`

Running the same command with swaylock will lock the screen and prompt you for a password and when you unlock, the rest of the command will be run and the computer will be suspended without a password on next startup.

Is this a security feature of swaylock or a bug? Is it possible to get it to work as i3lock?

**Comment by RedSoxFan** [comment]
Use `swaylock -f` (https://github.com/swaywm/swaylock/blob/master/swaylock.1.scd#L33)
