### ISSUE TITLE
Proposal: Provide a period of grace 

### ISSUE THREAD

**Issue by schauveau** [swaywm/swaylock#58]

**Comment by emersion** [comment]
Duplicate of https://github.com/swaywm/swaylock/issues/50

**Comment by schauveau** [comment]
The lockscreen can be annoying for example while watching a video. It would be nice to be able to delay the actual locking for a few seconds to give people the time to press a key or mouse their mouse.

**Comment by emersion** [comment]
Yes. #50 suggests a way to do this.

**Comment by emersion** [comment]
Question: how do people using i3 do this?

**Comment by schauveau** [comment]
I don't know. Never used i3. 
A simple way is probably to kill the swaylock process from a resume event in swayidle.

**Comment by smlx** [comment]
@emersion I use light-locker, which has an option to delay locking the screen.
https://manpages.debian.org/unstable/light-locker/light-locker.1.en.html

**Comment by emersion** [comment]
Looks like a Wayland equivalent to this would be nice to have.

**Comment by emersion** [comment]
This small client may be used to implement a grace period: https://git.sr.ht/~emersion/chayang

**Comment by bencollerson** [comment]
Above mentioned, chayang is a much better way to implement a grace period. Keeping unnecessary complexity out of a screen locker is better for security anyway.
