### ISSUE TITLE
Invert --show-keyboard-layout option

### ISSUE THREAD

**Issue by jeremiah-miller** [swaywm/swaylock#60]
Is there any possibility of an option like --show-keyboard-layout, but where it hides the keyboard layout even if there are multiple activated?

Thanks!

**Comment by emersion** [comment]
Yeah.

**Comment by jeremiah-miller** [comment]
I decided to take a look at it and see if I couldn't add it myself. Is [this guide](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) a good one to follow if I want to submit my changes? Thanks!

**Comment by ddevault** [comment]
https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md

**Comment by jeremiah-miller** [comment]
Sorry if this is a really basic question, I added a hide-keyboard-layout option but I noticed that in the generated swaylock.1.scd man page, it automatically added the show-keyboard-layout information but not the hide-keyboard-layout option that I added. Did I miss something when adding the option? 

Here's what I've got so far
https://github.com/jeremiah-miller/swaylock/commit/86f4fea55e2f9f3503fdc00245b270bff19fd2fc

Thanks!

**Comment by ddevault** [comment]
`swaylock.1.scd` is not generated, it's written by hand and a roff document (man page) is generated from it.

**Comment by ddevault** [comment]
man scdoc

**Comment by jeremiah-miller** [comment]
Ah I see, I'll update that then. Is there anything else I need to change to add this option?

**Comment by ddevault** [comment]
I'll take a closer look when the pull request comes in.
