### ISSUE TITLE
Swaylock failing to lock outputs that are inactive

### ISSUE THREAD

**Issue by Salastil** [swaywm/swaylock#63]
Attempting to lock using swaylock yields endless spam in the terminal as it is trying to get data from an inactive output. It consistently rotates the name of the expected image in the tmp folder. In my case I have two active outputs, HDMI-A-2 and HDMI-A-3 used from the Internal GPU on my i5-6600k. I use the Nvidia GPU in passthrough to a Windows VM. This Windows output would be called DP-3. The output in question "DVI-D-1" refers to the DVI port on the Nvidia card that has no cables attached to it at all. I can't pin this to an exact package update. Swaylock was functional for me prior to Sway 1.0. Running swaymsg -t get_outputs does not show DVI-D-1 as a registered output, just the two HDMI ports. 

```
unknown output 'DVI-D-1'convert: no decode delegate for this image format `MUZWT0F2KP' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.MUZWt0F2kP' @ error/convert.c/ConvertImageCommand/3300.
convert: no decode delegate for this image format `OIIWVWUV3V' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.OIIwvwuv3v' @ error/convert.c/ConvertImageCommand/3300.
unknown output 'DVI-D-1'convert: no decode delegate for this image format `UBCNU76T2U' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.uBCnu76t2u' @ error/convert.c/ConvertImageCommand/3300.
convert: no decode delegate for this image format `CIBV0DKQPP' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.cIbV0DKqpP' @ error/convert.c/ConvertImageCommand/3300.
unknown output 'DVI-D-1'convert: no decode delegate for this image format `KWF9JRIHH0' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.Kwf9jriHh0' @ error/convert.c/ConvertImageCommand/3300.
convert: no decode delegate for this image format `0VNHWHHCBM' @ error/constitute.c/ReadImage/556.
convert: no images defined `/tmp/tmp.0VnhWhHcbm' @ error/convert.c/ConvertImageCommand/3300.
```

**Comment by emersion** [comment]
swaylock isn't supposed to call `convert`.

Can you run `swaylock -d >swaylock.log 2>&1` and upload the full log?

**Comment by Salastil** [comment]
[swaylock.log](https://github.com/swaywm/swaylock/files/3000837/swaylock.log)
The log appears to be more of the same. I have to kill the entire process using ctrl+c.

**Comment by Salastil** [comment]
Doing a bit more digging I've found that each cycle in the spam spawns a new tmp.stringhere file in /tmp/. All of these files are empty.

```
stat tmp.3ArYoVekbi 
  File: tmp.3ArYoVekbi
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 2eh/46d	Inode: 14917252    Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/    mega)   Gid: (  998/   wheel)
Access: 2019-03-24 17:00:47.875074982 -0400
Modify: 2019-03-24 17:00:47.865074937 -0400
Change: 2019-03-24 17:00:47.865074937 -0400
 Birth: -
```

**Comment by emersion** [comment]
Something seems wrong with your setup. This is what I get when I run `swaylock -d`:

```
2019-03-24 23:11:05 - [main.c:1067] Parsing CLI Args
2019-03-24 23:11:05 - [main.c:278] output name is LVDS-1
```

Since you don't even have the first line, it doesn't seem like you're running swaylock.
