### ISSUE TITLE
Cannot type password again immediately after failed attempt

### ISSUE THREAD

**Issue by minus7** [swaywm/swaylock#66]
When you try to unlock the screen but get the password wrong, you have to wait until the 'wrong' indicator goes away. Xscreensaver allows you to start typing again while this message is shown and I'd like to see the same behavior in swaylock.

**Comment by Qiu3344** [comment]
I think it's supposed to be like that. It makes it harder to brute-force your password.

**Comment by emersion** [comment]
>It makes it harder to brute-force your password.

no

**Comment by markstos** [comment]
"No", @emersion ? If a password takes longer to brute force, I would say that's qualifies as being "harder".

**Comment by Crandel** [comment]
I would like to have smaller timeout or configure it somehow, because my attempts failed very often, because I use two layouts one of them is Cyrillic and very often it happens during working meetings

**Comment by emersion** [comment]
> "No", @emersion ? 

There's no real reason why swaylock needs to block during a pending auth attempt. We could allow the user to start typing the next password.

> I would like to have smaller timeout

The timeout is enforced by PAM. PAM probably offers a way to configure this.

**Comment by Crandel** [comment]
For anybody, who wants to avoid delays after first attempt I found a solution how to configure PAM
File: `/etc/pam.d/system-auth` add **nodelay** to the end
```
auth            sufficient      pam_unix.so try_first_pass nullok nodelay
```

**Comment by tmpm697** [comment]
It's weird that I don't have this behavior with `slock` on X11, `slock` allows me type password immediately and does not failed stack at all. Like I can type 100 times fails and type password immediately.

Is there a way to not mess with `pam`? or a way that `slock` currently implement?

Prevent `Brute-force` may be wanted but sometime we don't.

**Comment by kennylevinsen** [comment]
You can configure your PAM stack however you want. Feel free to construct one that doesn't call pam_faillock. You can even steal the one from slock. The one you're using for swaylock probably just `include` premade stacks on your system which themselves use pam_faillock.

See /etc/pam.d, and `man pam`. There is no reasonable way to avoid PAM.

I'll close this issue as there is nothing for swaylock to do, but feel free to open an issue/submit a patch for the lacking info message.
