### ISSUE TITLE
Asserion failed

### ISSUE THREAD

**Issue by regfaker** [swaywm/swaylock#69]
Hi,
swaylock fails immediately on assertion:
version https://github.com/swaywm/swaylock/commit/98e5afe364776d06017579e14f972be6f65fbb8b
```
$ swaylock -d
2019-04-03 10:57:17 - [main.c:1018] Parsing CLI Args
swaylock: ../main.c:1054: main: Assertion `state.compositor && state.layer_shell && state.shm' failed.
Aborted
```

external monitor
```
$ xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
XWAYLAND1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 480mm x 270mm
   1920x1080     59.96*+
```
Gnome 3.30.2, Debian buster

Thanks for investigating. Please let me know if there is some additional info I can give.

**Comment by emersion** [comment]
GNOME doesn't support the layer-shell protocol. You should probably ask them to add this feature.

**Comment by regfaker** [comment]
Ok, asked https://gitlab.gnome.org/GNOME/gnome-shell/issues/1141
Thanks

**Comment by soloturn** [comment]
created https://gitlab.gnome.org/GNOME/mutter/issues/1053
