### ISSUE TITLE
Turn off all, but the alphanumeric keyboard?

### ISSUE THREAD

**Issue by chzzzh** [swaywm/swaylock#71]

**Comment by emersion** [comment]
Why?

**Comment by chzzzh** [comment]
It reacts and looks on the screen like I pressed some keys by mistake.

**Comment by emersion** [comment]
Wait, what would be this feature about exactly? Ignore keypresses from a _part of the keyboard_?

**Comment by chzzzh** [comment]
Exactly.

**Comment by emersion** [comment]
I'm not a fan of this. It could easily lock users out if they need to insert non-ASCII letters or switch layouts, and I'm not convinced of its usefulness.

**Comment by chzzzh** [comment]
Oh, true. So would be better when the key is entered, then swaylock should react.

**Comment by rumpelsepp** [comment]
One use case might be that switching virtual terminals (ctrl+alt+f1, ctrl+alt+f2, ...) can be locked when swaylock is active.

**Comment by ddevault** [comment]
I didn't notice this issue, but it doesn't make sense to do this. Switching to other virtual terminals isn't a problem, since they'll be locked behind a getty.

**Comment by rumpelsepp** [comment]
> Switching to other virtual terminals isn't a problem, since they'll be locked behind a getty.

Only if there is no login session active^^. IIRC the gnome screenlocker somehow blocks switching to virtual terminals when it's active.

**Comment by chzzzh** [comment]
So how about reacting only to an entered letter, not to any key?
