### ISSUE TITLE
Can't use Ctrl+m to confirm password

### ISSUE THREAD

**Issue by gbrlsnchs** [swaywm/swaylock#75]
The last screen locker I used was `xscreensaver`, in which I could confirm the password typed with `Ctrl+m`. `swaylock` only allows me to press `Enter` instead. :disappointed:

This is by far not a big deal. But why doesn't `Ctrl+m` works the same as `Enter`? It would be nice to have it working with `Ctrl+m`.

**Comment by ddevault** [comment]
We support `^d` for this, but I mean, fuck it, why not? If you send a patch adding another it'll get merged.
