### ISSUE TITLE
Notifications displayed on top of swaylock

### ISSUE THREAD

**Issue by tardypad** [swaywm/swaylock#77]
Using sway 1.0, swaylock 1.3 and mako 1.3 on Arch Linux.

I'm using mako configured to display notifications in an "overlay layer", which is meant to have notifications displayed above fullscreen windows.
I've found out however that this also results in the notifications being displayed on top of swaylock, which I would consider being an issue.

I'm not sure where this should be reported though. I would guess the problem belongs in sway or swaylock which should prevent any such above display when the screen is locked.
Let me know if this issue should be moved to another project.

**Comment by judemille** [comment]
Same issue exists with hyprland, swaylock, and dunst.

**Comment by tmccombs** [comment]
Is this resolved now after https://github.com/swaywm/swaylock/pull/219?

**Comment by tardypad** [comment]
Just tested again using sway 1.8, swaylock 1.7 and mako 1.7.1 and the issue doesn't appear anymore for me.
I'm closing the issue then.
