### ISSUE TITLE
Usability: visual notification of impending lock (fade)

### ISSUE THREAD

**Issue by edrex** [swaywm/swaylock#79]
When a lock is about to happen, visually indicate this in some way so the user can preempt the lock, avoiding the need to retype their password. Other environments use a "fade to black" to indicate an impending lock. I guess this would be "fade to background".

This would alleviate user pain due to lack of inhibit support in various applications (fullscreen video in Firefox), which makes undesired locks common.

**Comment by ddevault** [comment]
>This would alleviate user pain due to lack of inhibit support in various applications (fullscreen video in Firefox), which makes undesired locks common.

This is a bug in firefox: they should use idle-inhibit.

**Comment by emersion** [comment]
>When a lock is about to happen, visually indicate this in some way so the user can preempt the lock, avoiding the need to retype their password. Other environments use a "fade to black" to indicate an impending lock. I guess this would be "fade to background".

Duplicate of https://github.com/swaywm/swaylock/issues/58
