### ISSUE TITLE
Mitigate unresponsive keyboard after sleep

### ISSUE THREAD

**Issue by schauveau** [swaywm/swaylock#83]
On my laptop, I noticed that the keyboard has an erratic behavior when resuming from sleep. After a few seconds of black screen the screen appears, the keyboard works during about 1 second, stops working during a 1 or 2 seconds and then start working again. For instance, when I quickly type '1' to '9' after resume I typically get something like '34789'. The missing '12' are expected but the missing '56' are a bit annoying. I lost count of the number of times I missed my password because of that.  

The console shows the same behavior so this is not specific to wayland or swaylock. I assume that this is because the linux kernel is reinitializing the input devices (though libinput does not report any device change).

So I do not expect that swaylock can fix that behavior but it would be nice to have a way to mitigate the effect. Swaylock probably has no ways to know when the keyboard is actually ready so a simple workaround could be to display a black screen for a few seconds without accepting keyboard events. The delay would be specified on the command line and would be zero by default.

**Comment by ddevault** [comment]
I think you should fix your hardware. This is definitely not our bug.
