### ISSUE TITLE
pam config install dir

### ISSUE THREAD

**Issue by towoe** [swaywm/swaylock#85]
On my Arch Linux machine the `swaylock` pam file is installed to `/usr/local/etc/pam.d/` if I use ninja to install from source and if the meson option `--prefix /usr` is not given.
If I use the prefix option it goes to `/etc/pam.d/` as it should be.
I am not entirely sure if this is the expected behavior, but it seems strange to me.

**Comment by emersion** [comment]
This is how prefix works: installation won't put anything outside of it. Generally when you install to `/usr/local` you need to configure your `PATH` and dynamic linker. This also applies to PAM but it doesn't seem like upstream PAM has a way to include another directory.

However you can override `sysconfdir` to `/etc` if you want.

**Comment by towoe** [comment]
Ok, thanks for explanation!
