### ISSUE TITLE
Unlock failure callback?

### ISSUE THREAD

**Issue by lovesegfault** [swaywm/swaylock#93]
Just an idea I had, it would be interesting if the user could set a script/exec to run on each password entry failure. My motivation for this is I'd like to get a snapshot with the camera, and then attempt to upload it to my VPS. Of course I'm sure many other creative uses for this feature must exist, so it might be worth considering

**Comment by ddevault** [comment]
This would be nice for a swaylock fork, but I'd rather keep it simple upstream.
