### ISSUE TITLE
Swaylock fallbacks to desktop on crash

### ISSUE THREAD

**Issue by chzzzh** [swaywm/swaylock#97]

**Comment by emersion** [comment]
How do you make swaylock crash?

**Comment by chzzzh** [comment]
Idk, just turned the lid on and it didn't show the circle. Yet would be nice to close the session on any crash.

**Comment by emersion** [comment]
I'm not a fan of this idea.

**Comment by chzzzh** [comment]
But if it doesn't, it's compromising the user's desktop?

**Comment by emersion** [comment]
One could wrap `swaylock` in a script that exits sway if its child process crashes.

**Comment by xorgy** [comment]
Seems like the layer shell protocol should be extended, or a new screen locking protocol should be produced, which makes it not possible for the compositor to show the desktop unless it receives explicit confirmation of a successful unlock.

**Comment by ddevault** [comment]
I'm not interested in trying to gracefully deal with a swaylock crash. There's nothing graceful about crashing.

**Comment by alecmev** [comment]
> One could wrap `swaylock` in a script that exits sway if its child process crashes.

How would one go about integrating this with `swaylock`? I've been unable to find out the PID of the daemon in a non-"stringly typed" way (i.e. not `ps -C swaylock`), so I can't know when it terminates.

**Comment by emersion** [comment]
PIDs are racy, so I'd rather not do that.

Instead, you can either not use `-f`, either somehow use `pgrep -P` to get the child process PID.

A notification mechanism that doesn't involve forking is discussed in https://github.com/swaywm/swaylock/pull/42

**Comment by alecmev** [comment]
> Instead, you can either not use `-f`

Ah, I mistyped, meant integrating with `swayidle`, which needs `-f` to function properly.

> somehow use `pgrep -P` to get the child process PID

The parent is gone by the time I'm able to run `pgrep -P`, so I can't match the child with a PPID.

> A notification mechanism that doesn't involve forking is discussed in #42

Promising! Shame it's stale.

**Comment by alecmev** [comment]
Any other suggestions, please? Doesn't seem like #42 is going anywhere, and `swaylock` still crashes sometimes.
